BNS\App\CampaignBundle\Model\Campaign:
  exclusion_policy: All
  virtual_properties:
    getTypeName:
      expose: true

    getRichMessage:
      expose: true
      serialized_name: message

    getNumberOfSentMessages:
      expose: true
      groups: [campaign_detail]
      serialized_name: nb_sent

    getNotSentMessages:
      expose: true
      groups: [campaign_detail]
      serialized_name: not_sent

  relations:
    - rel: attachments
      embedded:
        content: expr(object.getResourceAttachments())
        exclusion:
          groups: [ campaign_attachment ]
