BNS\App\CoreBundle\Model\User:
  exclusion_policy: All
  virtual_properties:
    getFullName:
      expose: true
      groups: [Default, list, user_list, detail, user_detail, user_basic ]
    getAvatarUrl:
      expose: true
      groups: [ list, user_list, detail, user_detail, media_search, lsu_avatar, user_avatar ]
    getAvatarResource:
      expose: true
      serialized_name: avatar
      groups: [ list, detail, user_detail ]
    getGender:
      expose: true
      groups: [ detail, user_detail, lsu_gender ]
    isAdult:
      expose: true
      groups: [ detail, user_detail ]
    isChild:
      expose: true
      groups: [ detail, user_detail, competition_statistics ]
    getFavoriteGroupId:
      expose: true
      groups: [me]
    getBeta:
      expose: true
      groups: [me]
    getBirthdayDate:
      expose: true
      groups: [lsu_birthday]
      serialized_name: birthday
    getLastName:
      expose: true
      groups: [ olympics_training_user_detail ]
    getAlias:
      expose: true
      groups: [ user_messages ]

  relations:
    - rel: profile
      href: expr(service('bns.user_directory.manager').getProfileUrl(object))
      exclusion:
        groups: [ list, user_list, detail, user_detail ]
        exclude_if: expr(!isset("profile_link"))
    - rel: children
      embedded:
        content: expr(object.getActiveChildren())
        exclusion:
          groups: [ user_children_preview ]
          exclude_if: expr(object.isChild())
