imports:
    - { resource: config_app.yml }
    - { resource: parameters_prod.yml }

# /!\ Settings here CAN'T BE OVERRIDDEN
# DO NOT ADD settings here unless you have a very good reason

assetic:
    use_controller: false
    java: "java"

framework:
    trusted_proxies:  %trusted_proxies%
    session:
      cookie_httponly:  true
      cookie_secure:    true
    # Setting assets version here is deprecated. Prefer using config.yml
#    assets:
#      version: v190
      # Fix me
      #base_urls: [@bns.parameter.cdn_url]

twig:
  debug:            %kernel.debug%
  globals:
    cdn_url: @bns.parameter.cdn_url

#propel:
#    dbal:
#        default_connection: app
#        connections:
#            app:
#                driver:     %database_driver%
#                user:       %app_database_user%
#                password:   %app_database_password%
#                dsn:        %database_driver%:host=%database_host%;dbname=%app_database_name%;charset=UTF8
                #Si besoin de mettre en place slave / master
                #slaves:
                #    slave1:
                #        user:       %app_database_user%
                #        password:   %app_database_password%
                #        dsn:        %database_driver%:host=%database_host_slave%;dbname=%app_database_name%;charset=UTF8
                #    slave2:
                #        user:       %app_database_user%
                #        password:   %app_database_password%
                #        dsn:        %database_driver%:host=%database_host%;dbname=%app_database_name%;charset=UTF8
monolog:
    channels: [account_link]
    handlers:
        main:
            type: rotating_file
            max_files: 10
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
            channels: ['!account_link']
        mailer:
            type: stream
            level: error
            path:  %kernel.logs_dir%/mailer_%kernel.environment%.log
        account_link:
            type: rotating_file
            max_files: 10
            level: info
            path:  %kernel.logs_dir%/account_link_%kernel.environment%.log
            channels: [account_link]

knp_snappy:
    pdf:
        binary:     'LANG=fr_FR.UTF-8 /usr/local/bin/wkhtmltopdf'
    image:
        binary:     'LANG=fr_FR.UTF-8 /usr/local/bin/wkhtmltoimage'

# /!\ THIS CAN'T BE OVERRIDDEN
# DO NOT ADD parameters here unless you have a very good reason
parameters:
    public_version_url:                  https://beneylu.com
    bns_breakfast_item_id: 2
