imports:
    - { resource: config.yml }
    - { resource: security_app.yml }
    
framework:
    router:   { resource: "%kernel.root_dir%/config/routing_app.yml" }
    
    csrf_protection:
        enabled:              true
        field_name:           _token
    
propel:
    dbal:
        default_connection: app
        connections:
            app:
                driver:     %database_driver%
                user:       %secret_app_database_user%
                password:   %secret_app_database_password%
                dsn:        %database_driver%:host=%database_host%;dbname=%app_database_name%;charset=UTF8
    build_properties:
        propel.useDateTimeClass: true
        propel.dateTimeClass: \BNS\App\CoreBundle\Date\ExtendedDateTime
        propel.mysql.tableType: InnoDB
        propel.packageObjectModel: true
    behaviors:
        typehintable: vendor.willdurand.TypehintableBehavior.src.TypehintableBehavior
        bns_resource_attachmentable: src.BNS.App.ResourceBundle.Propel.BNSResourceAttachmentableBehavior
        extra_properties: vendor.CarpeHora.ExtraPropertiesBehavior.src.ExtraPropertiesBehavior
        bns_templatable: src.BNS.App.TemplateBundle.Propel.BNSTemplatableBehavior

old_sound_rabbit_mq:
    connections:
        default:
            host:      '%rmq_host%'
            port:      '%rmq_port%'
            user:      '%secret_rmq_user%'
            password:  '%secret_rmq_password%'
            vhost:     '%rmq_vhost%'
    producers:
        mailer:
            connection: default
            exchange_options:
                name: 'mailer'
                type: direct
                auto-delete: false
                durable: true
                internal: false
    consumers:
        mailer:
            connection: default
            exchange_options:
                name: 'mailer'
                type: direct
                auto-delete: false
                durable: true
                internal: false
            queue_options:
                name: 'mailer'
            callback:         mailer_consumer
            
services:
    # Surcharge du UserProvider du KNPOAuthBundle
    # default:
    #  - class: %knp_oauth.user.provider.entity.class%
    #  - parent: doctrine.orm.security.user.provider
    knp_oauth.user.provider.entity:
         class: BNS\App\CoreBundle\Security\Core\UserProvider\ModelUserProvider
         #parent: BNS\App\CoreBundle\Security\Propel\ModelUserProvider
         
    bns.controller_listener:
        class: BNS\App\CoreBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController, priority:-255 }
        arguments: [@annotation_reader]
    
    
    #propel.orm.security.user.provider:
      #class: Propel\PropelBundle\Security\User\ModelUserProvider
      #public: false
      #abstract: false    
    
# @see: https://github.com/stfalcon/TinymceBundle
stfalcon_tinymce:
    tinymce_buttons:
        resource: 
            title: "Ressources"
            image: /medias/images/resource/tiny_icon.png
    include_jquery: false
    textarea_class: "load_tinymce"
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "justifyleft,justifycenter,justifyright,justifyfull,separator,bold,italic,underline,strikethrough,formatselect,fontselect,fontsizeselect"
            theme_advanced_buttons2: "bullist,numlist,separator,undo,redo,separator,forecolor,backcolor,separator,link,unlink,separator,fullscreen,emotions,image,resource"
            theme_advanced_buttons3: ""
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            theme_advanced_resizing : "true"
            plugins: "advimage,advlink,emotions,inlinepopups"
            theme_advanced_buttons1_add: ""
            paste_auto_cleanup_on_paste: true
            handle_event_callback : "onTinyMCEKeypress"
            body_class : "body_tinymce"
            content_css : "/medias/css/manager.css"
            height: "480"
            width: "100%"
            language: "fr"
        no_resources:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "justifyleft,justifycenter,justifyright,justifyfull,separator,bold,italic,underline,strikethrough,formatselect,fontselect,fontsizeselect"
            theme_advanced_buttons2: "bullist,numlist,separator,undo,redo,separator,forecolor,backcolor,separator,link,unlink,separator,fullscreen,emotions"
            theme_advanced_buttons3: ""
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            theme_advanced_resizing : "true"
            plugins: "advlink,emotions,inlinepopups"
            theme_advanced_buttons1_add: ""
            paste_auto_cleanup_on_paste: true
            handle_event_callback : "onTinyMCEKeypress"
            body_class : "body_tinymce"
            content_css : "/medias/css/manager.css"
            height: "480"
            width: "100%"
            language: fr
            
bns_app_autosave:
    # Default timer before the autosave is launched, in seconds
    default_timer: 60
    # Default number of letter before the autosave is launched
    default_keypress: 50
    
vich_geographical:
    db_driver: orm
    templating:
        info_window: BNSAppGPSBundle:Front:infoWindow.html.twig
        
hwi_oauth:
    firewall_name: oauth_area

knp_snappy:
    pdf:
        enabled:    true
        options:    []
    image:
        enabled:    true
        options:    []

parameters:
    available_languages:
        - en
        - fr
        
    session_listener.class: BNS\App\CoreBundle\Listener\SessionListener
    
    # OAuth authentification
    
    # Id du domaine sur la centrale
    domain_id: %bns_domain_id%
    domain_name: %bns_domain_name%
    
    # Environnement de l'application
    application_environment:
    
    #Paramètres pour les ressources
    #mode de stockage : local || s3 (pour l'instant)
    resource_storage:                   %bns_resource_storage%
    resource_files_dir:                 %kernel.root_dir%/data/resources
    uploaded_files_dir:                 %kernel.root_dir%/../web/uploads
    csv_import_files_tmp_dir:						%kernel.root_dir%/data/temp/
    resource_temp_dir:                  %kernel.root_dir%/data/
    #Clé d'utilisation pour AWS (en dev uniquement sur bucket de dev)
    bns3.aws_key:                       %secret_bns_bns3.aws_key%
    bns3.aws_secret_key:                %secret_bns_bns3.aws_secret_key%
    bns3.s3.bucket_name:                %bns_bns3.s3.bucket_name%
    tools_dir:                          %kernel.root_dir%/Tools/

