imports:
    - { resource: config_app.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

propel:
    dbal:
        default_connection: app
        connections:
            app:
                driver:     %database_driver%
                user:       %app_database_user%
                password:   %app_database_password%
                dsn:        %database_driver%:host=%database_host%;port=%database_port%;dbname=%app_database_name%;charset=UTF8
            stat:
                driver:     %database_driver%
                user:       %stat_database_user%
                password:   %stat_database_password%
                dsn:        %database_driver%:host=%database_host%;port=%database_port%;dbname=%stat_database_name%;charset=UTF8
            auth:
                driver:     %database_driver%
                user:       %auth_database_user%
                password:   %auth_database_password%
                dsn:        %database_driver%:host=%database_host%;port=%database_port%;dbname=%auth_database_name%;charset=UTF8

monolog:
    channels: [account_link]
    handlers:
        account_link:
            type: rotating_file
            max_files: 10
            level: info
            path:  %kernel.logs_dir%/account_link_%kernel.environment%.log
            channels: [account_link]

bns_app_core:
    application_management:
        enabled: true
        auto_install: false
        uninstall_disabled: false

knp_snappy:
    pdf:
        binary:     %knp_snappy_pdf_binary%
    image:
        binary:     %knp_snappy_image_binary%
