#Fichiers de tous les identifiants / mots de passes utilisés dans les applications : NE PAS VERSIONNER !
parameters:
  # Databases
  secret_app_database_user: 
  secret_app_database_password: 
  #mailer
  secret_mailer_user: 
  secret_mailer_password: 
  #swift
  secret_swift_password: 
  # Symfony
  secret_symfony_secret: 
  #RMQ
  secret_rmq_user: 
  secret_rmq_password: 
  #Oauth
  secret_oauth_client_secret: 
  secret_oauth_security_client_id: 
  secret_security.logout.username.secret_key: 
  #Resources
  secret_bns_bns3.aws_key: 
  secret_bns_bns3.aws_secret_key: 