parameters:
#    bns_app_group.example.class: BNS\App\GroupBundle\Example

services:
#    bns_app_group.example:
#        class: %bns_app_group.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
