parameters:
    oauth_client_secret: devsecret
    oauth_security_client_id: 1_000001
    application_base_url: http://beneylu.dev/ent
    check_group_validated: true
    show_alert: false
    url_prefix: ent
#    logon.custom_view: BNSAppMainBundle:Logon:logon_main.html.twig
    logon.custom_view: BNSAppMainBundle:Logon:logon_main_ajax.html.twig
    has_yerbook: true
    #fos_js_routing.request_context_base_url: ent/
    bns.enable_register: true
    disable_password_wheel: true
    import_ent1d:
      alpi:
        name: Landecoles
        parent: 1
        aaf_dir: %kernel.root_dir%/data/importENT1D/
        folder_suffix: "_040"
        emails: ['eymeric.taelman@gmail.com','eymeric.taelman@pixel-cookers.com']
    #Options pour le suivi analytics
    analytics_enabled: true
    paas_use: true
    default_portal_class: ac-mtp
    has_medialandes: true
    show_evaluent: true
    #check_group_enabled: true
    breakfast_order_prefix: BDEV-
    yb_order_prefix: YBDEV-
    bns_beta_allowed: true
    bns_beta_enabled: false
    bns_beta_domain: beta.beneylu.dev
    bns_normal_domain: beneylu.dev
    bns_api_cache_key: 123456
    bns_spot_api_secret_key: validSpotSecretKey

bns_app_core:
    application_management:
        enabled: true
        auto_install: false
        uninstall_disabled: false
