parameters:
#    bns_app_profile.example.class: BNS\App\ProfileBundle\Example

services:
#    bns_app_profile.example:
#        class: %bns_app_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
