BNS\App\UserDirectoryBundle\Model\DistributionList:
  exclusion_policy: All

  virtual_properties:
    getRoleTypes:
      expose: true
      groups: [ detail ]
      serialized_name: roles
    getGroupIds:
      expose: true
      groups: [ detail ]
