BNS\App\CompetitionBundle\Model\CompetitionBookQuestionnaire:
  exclusion_policy: All
  properties:
    created_at:
      expose: true
      groups: [competition_detail]

  virtual_properties:
    getQuestionnaire:
      expose: true
      groups: [competition_detail]
    getUser:
      expose: true
      groups: [competition_detail]
