BNS\App\CompetitionBundle\Model\PedagogicCourse:
  exclusion_policy: All

  relations:
    - rel: books
      embedded:
        content: expr(object.getBooks())
        groups: [ competition_detail ]
