parameters:
#    bns_app_hello_world.example.class: BNS\App\HelloWorldBundle\Example

services:
#    bns_app_hello_world.example:
#        class: %bns_app_hello_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
