var i18n = $.extend({}, i18n || {}, {
  xgcalendar: {
    dateformat: {
      "fulldaykey": "MMddyyyy",
      "fulldayshow": "L d yyyy",
      "fulldayvalue": "M/d/yyyy",
      "Md": "W",
      "Md3": "L d",
      "separator": "/",
      "year_index": 2,
      "month_index": 0,
      "day_index": 1,
      "day": "d",
      "sun": "Domingo",
      "mon": "lunes",
      "tue": "Martes",
      "wed": "Miércoles",
      "thu": "Jueves",
      "fri": "Viernes",
      "sat": "Sábado",
      "jan": "Ene",
      "feb": "Feb",
      "mar": "Mar",
      "apr": "Abr",
      "may": "May",
      "jun": "Jun",
      "jul": "Jul",
      "aug": "Ago",
      "sep": "Sep",
      "oct": "Oct",
      "nov": "Nov",
      "dec": "Dic"
    },
    "no_implemented": "No implemented yet",
    "to_date_view": "Click para ver esta fecha",
    "i_undefined": "Undefined",
    "allday_event": "Evento ocupa todo el día",
    "repeat_event": "Repetir evento",
    "time": "Hora",
    "event": "Evento",
    "location": "Locación",
    "participant": "Participantes",
    "get_data_exception": "Ocurrió una excepción al obtener el evento.",
    "new_event": "Evento nuevo",
    "confirm_delete_event": "¿ Confirma la eliminación del evento ? ",
    "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
    "data_format_error": "Data format error! ",
    "invalid_title": "Título del evento no puede ser nulo o contener ($<>)",
    "view_no_ready": "View is not ready",
    "example": "Por ej. Cobrar cuando se realice.",
    "content": "Observación",
    "create_event": "Crear evento",
    "update_detail": "Editar detalles",
    "click_to_detail": "Ver detalles",
    "i_delete": "Eliminar",
    "day_plural": "días",
    "others": "Otros",
    "item": ""
  }
});
