var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dimanche",
            "mon": "lundi",
            "tue": "Mardi",
            "wed": "Mercredi",
            "thu": "Jeudi",
            "fri": "Vendredi",
            "sat": "Samedi",
            "jan": "Janvier",
            "feb": "Février",
            "mar": "Mars",
            "apr": "Avril",
            "may": "Mai",
            "jun": "Juin",
            "jul": "Juillet",
            "aug": "Août",
            "sep": "Septembre",
            "oct": "Octobre",
            "nov": "Novembre",
            "dec": "Décembre"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "Toute la journée",
        "repeat_event": "Récurrent",
        "time": "Date et horaire",
        "event": "Evènement",
        "location": "Lieu",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "What",
        "create_event": "Créer un évènement",
        "update_detail": "Edit details",
        "click_to_detail": "View details",
        "i_delete": "Delete",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
