event:
  - 1:
    title: Library
    content: Don't forget to bring back your library books ;-)
    start: 14
    end: 16
  - 2:
    title: Sport
    content: This week we will start running.
    start: 10
    end: 12
  - 3:
    title: Swimming Pool
    content: Bring your googles!
    start: 9
    end: 11
  - 4:
    title: Music
    content: Choir.
    start: 10
    end: 11
  - 5:
    title: Gardening
    content: This week we will plant carrots.
    start: 13
    end: 15
  - 6:
    title: Birthday Party
    content: We will eat chocolate cake!
    start: 15
    end: 16
  - 7:
    title: Write to our foreign correspondants 
    content: This week we will introduce ourselves.
    start: 9
    end: 11
  - 8:
    title: Visit to the zoo
    content: Bring your cameras.
    start: 15
    end: 16
  - 9:
    title: Preparation of the fair
    content: We will make paper decorations
    start: 10
    end: 12
  - 10:
    title: Inter-class football 
    content: Competition time!
    start: 16
    end: 18
  - 11:
    title: Introduction to African dance
    content: Take your sports equipment.
    start: 9
    end: 12
  - 12:
    title: Puppet show
    content: With the puppet company
    start: 14
    end: 16
  - 13:
    title: Sport
    content: This week we will do karate.
    start: 10
    end: 12
  - 14:
    title: Highway code workshop
    content: It will take place in the courtyard by bicycle.
    start: 14
    end: 15
  - 15:
    title: Journalism workshop
    content: Volunteers for the school newspaper.
    start: 11
    end: 12
  - 16:
    title: Film sound effects workshop
    content: On the film Kung Fu Panda 3.
    start: 17
    end: 18
  - 17:
    title: Spelling test
    content: A test of 100 words.
    start: 8
    end: 10
  - 18:
    title: Stories
    content: With the librarians.
    start: 14
    end: 16
  - 19:
    title: Gardening
    content: This week we will be weeding.
    start: 13
    end: 15
  - 20:
    title: Art
    content: Painting with watercolours.
    start: 10
    end: 12
  - 21:
    title: Racing
    content: May the best man win!
    start: 14
    end: 16
  - 22:
    title: Cinema
    content: We will watch Finding Dory.
    start: 13
    end: 16
  - 23:
    title: Swimming Pool
    content: We will learn to put our heads under water.
    start: 9
    end: 11
  - 24:
    title: Science
    content: This week we will learn about plants.
    start: 8
    end: 10
  - 25:
    title: Food
    content: We will make pizza.
    start: 10
    end: 12
  - 26:
    title: French
    content: Learning how to count to 20.
    start: 9
    end: 10
  - 27:
    title: Music
    content: We will do a precussion.
    start: 10
    end: 11
  - 28:
    title: IT
    content: Writing on the Beneylu School blog.
    start: 14
    end: 16
  - 29:
    title: Sport
    content: This week we will learn gymnastics.
    start: 9
    end: 10
  - 30:
    title: Art
    content: Painting portraits.
    start: 13
    end: 15
