blog:
 - 1:
   title: Our morning at the swimming pool!
   content: >
     <p>On Tuesday we all went to the <span style="font-size: large;"><strong>swimming pool</strong></span>. We took our <strong>swimming costumes</strong> and our <strong>goggles</strong>. We laughed a lot and learned how to swim.</p>  <p>We weren't allowed to run by the edge of the pool, it's very dangerous because you can slip.</p>  <p>Three of us managed to put our heads under the water, next week more of us will do it!</p>  <p>We already want to go back&nbsp;<img title="Sealed" src="https://beneylu.com/ent/bundles/stfalcontinymce/vendor/tiny_mce/plugins/emotions/img/smiley-sealed.gif" alt="Sealed" border="0">&nbsp;!</p>
   images:
     - pool.jpg
     - pool1.jpg
     - pool2.jpg
   comments:
     - It's great that the little ones are being sporty!
     - You can put your head under water with your goggles!
     - I like to jump off the diving board!
     - I managed to put my head under the water but i was a little scared ;-)
   category: Sport
 - 2:
   title: Gardening
   content: >
     <p style="text-align: justify;">This week our garden was full of beautiful colours.</p>  <p style="text-align: justify;">It's spring and our flowers are growing well! In June, we planted carrot seeds, we will make a tasty salad!</p>  <p><img title="Tongue out" src="https://beneylu.com/ent/bundles/stfalcontinymce/vendor/tiny_mce/plugins/emotions/img/smiley-tongue-out.gif" alt="Tongue out" border="0"></p>
   images:
     - garden.jpg
   comments:
     - We planted an avocado pit at home! We will bring it into school for the garden.
     - We love picking strawberries - yum!
   category: Outdoor Activities
 - 3:
   title: Our visit to the library!
   content: >
     <p>Today we went to the library. We listened to 4 stories then we asked questions. Then we got to choose 5 books each to take home. We also got to make beautiful bookmarks.</p>
   images:
     - library.jpg
     - library1.jpg
   comments:
     - I love reading and listening to stories at the library.
   category:
 - 4:
   title: The Louvre
   content: >
     <p>Today we went to the Louvre museum. Our teacher told us about the history of art and the origins of the famous painting The Mona Lisa by Leonardo da Vinci </p>
     <p>"The portrait is of a young woman in the mountains. It is  a half length portrait and it has been said to be the most well known and most visited paintings in the world.</p>
   images:
     - louvre1.jpg
   comments:
     - The museum is very beautiful - great idea to go!
     - I love the painting of Mona Lisa it's very mysterious...
   category: Art
 - 5:
   title: Trip to the Zoo
   content: >
     <p>We went to the zoo for the end of year trip. We are very happy! We got to see the wild animals. We were a little afraid of the big cats, some of the others really wanted to go to see the zebras. We took some really nice photos for our "Safari" workshop.</p>
     <p>A bientôt !</p>
   images:
     - zoo1.jpg
     - zoo2.jpg
     - zoo3.jpg
   comments:
     - I was scared when the lion roared!
     - The lemur with its tongue hanging out was funny! Ahah !
   category: Sorties
 - 6:
   title: Spring week at school
   content: >
     <p>It is spring week at school. The pupils from class CP, CE1 and CE2 made paintings with flowers</p>  <p>The pupils from CM1 and CM2 took great pictures in the school garden and planted flowers.</p>
   images:
     - fleur1.jpg
   comments:
     - It's beautiful!
     - Finally springtime!
   category: At School
 - 7:
   title: Our Class Discovery of the Alps.
   content: >
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">This week our class went to visit the alps! The snow was amazing!</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr">&nbsp;</p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">In the morning we had class. We worked in the big room of our chalet, with a view of the mountains. This place is very beautiful, especially when the sun comes out. It makes you want to quickly finish your work !</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr">&nbsp;</p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">In the afternoon we went skiing. This is how we want to spend our free time. It was super ! We glided quickly through the snow and sometimes, we fell, but not very often. We also went sledging, it was quite easy but a lot of fun. Some of us even made igloos! (we also had a lot of snowball fights, even the teachers joined in!).</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">In the evening we organised a party. We chose music to dance to and we laughed a lot! We got to eat raclette, with lots of cheese, yum!</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr">&nbsp;</p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We learned a lot about the alps and had a lot of fun</span></p>
   images:
     - alpes1.jpg
     - alpes2.jpg
   comments:
     - Skiing was a lot of fun!
     - My favourite part was the snowball fights!
   category: Class Discovery
 - 8:
   title: Our Visit to the Palace of Versailles.
   content: >
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We visited the<strong>Palace of Versailles</strong>! It is located in the Yvelines. We learned that the palace was first built by Louis XIII as a hunting lodge.</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr">&nbsp;</p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The park at Versailles is very big and very beautiful. We had a picnic there on the lawn<strong</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We had a guide who told us about the history of the place and the people who lived there. Some of the stories were funny! For example, <strong>Louis XIV didn't wash</strong>, instead he used perfumes!</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We really loved; <strong>the Hall of Mirrors</strong> It was very beautiful!</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><span id="docs-internal-guid-8ef842a9-e6b3-2d75-c0c1-5c62f5b3239d"><span id="docs-internal-guid-8ef842a9-e6b3-495d-a474-93208324fe4b">&nbsp;</span></span></span></p>
   images:
     - versailles1.jpg
     - versailles2.jpg
     - versailles3.jpg
   comments:
     - Louis XIV also never brushed his teeth!
     - The castle is really impressive, I loved the hall of mirrors!
     - I prefer the park and the beautiful statues.
   category: Culture
 - 9:
   title: Sports Day
   content: >
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Today was sports day. We all competed at our favourite sports to win prizes</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Some of us ran a race for 1,5 km. We were given t-shirts and bibs with our names and numbers on them.</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We all did really well! </span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;"><strong id="docs-internal-guid-8ef842a9-e6c0-b3b9-dfef-99ed202f7153" style="font-weight: normal;">&nbsp;</strong></span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Quentin came first for the boys and Lola came first for the girls! Well done you two! And well done to everyone else!</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We had a lot of fun!</span></p>
   images:
     - run.jpg
   comments:
     - Well done to the champions!
     - Great competition!
   category: Competition
 - 10:
   title: The School Party
   content: >
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">Today we had a party at school!  </span></p>
     <p>&nbsp;</p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The pupils and the teachers all took part. We made masks to dress up. The girls made princess masks and the boys made Supermen masks. We had food and drinks and played games.</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">&nbsp;</span></p>
     <p style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;" dir="ltr"><span style="font-size: 15px; font-family: Arial; color:#000000; background-color: transparent; font-weight: normal; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">We can't wait till the next one!</span></p>
   images:
     - party.jpg
     - party1.jpg
   comments:
     - It was a great party! Everyone had cool masks
     - We threw confetti around so the floor was all colourful!
     - I made a vampire mask!
   category: Party
