name:
  - 5th Grade A
  - 4th Graders
  - Grade 1
  - 3rd Graders A
  - Grade 2 A
  - 5th Graders B
  - Grade 2 B
home_message:
  - Welcome to your digital class space
  - Hello, Bonjour, Hallo, Buenos Dias, namaste, buongiorno...
