gps:
  - 1:
    title: Castles around the world
    places:
      - 1:
        title: Prague Castle
        address: 119 08 Prague 1, Czech Republic
      - 2:
        title: Edinburgh Castle
        address: Castlehill, Edinburgh EH1 2NG, United Kingdom
      - 3:
        title: Matsumoto Castle
        address: Matsumoto Castle
  - 2:
    title: Medieval Towns
    places:
      - 1:
        title: Provins
        address: Provins France
      - 2:
        title: Mystras
        address: Mystras, Greece
      - 3:
        title: York
        address: York, England
  - 3:
    title: Famous Places
    places:
      - 1:
        title: L'arc de triomphe
        address: Place Charles de Gaulle, 75008 Paris
      - 2:
        title: Central Park
        address: Central Park Manhattan New York
      - 3:
        title: La Sagrada Familia
        address: Sagrada Familia
  - 4:
    title: Touristic Sites
    places:
      - 1:
        title: The Taj Mahal
        address: The Taj Mahal
      - 2:
        title: Niagara Falls
        address: Niagara Falls
      - 3:
        title: Stonehenge
        address: Stonehenge
  - 5:
    title: Unusual Places
    places:
      - 1:
        title: Mount Rushmore
        address: 13000 S Dakota 244, Keystone, SD 57751, America
      - 2:
        title: The Green Lake
        address: The Green Lake
      - 3:
        title: The Salt Desert, Bolivia
        address: The Salt Desert, Bolivia
