homework:
  - 1:
    subject: Geography
    homeworks:
      - 1:
        title: I know 5 countries in Europe
        content: I can tell you about 5 countries in Europe (such as the fashion, the people and the culture...)
        media: europe.gif
  - 2:
    subject: Sciences
    homeworks:
      - 1:
        title: Revise what you learned about wildlife
        content: Learn about kangaroos.
        media: kangaroo.jpg
      - 2:
        title: Read about the animal vocabulary
        content: Learn about these new words
        media: animals.jpg
  - 3:
    subject: French
    homeworks:
      - 1:
        title: Revision of the conjugation of the verb love in the past tense
        content: "<p>I know how to conjugate the verb aimer in the past tense.</p> <p>Give 4 example sentences.</p>"
        help: Taking the auxiliary "have" or "to be" in the present and we follow the past participle of the verb.
  - 4:
    subject: Reading
    homeworks:
      - 1:
        title: Read chapter 4 of your book
        content: "I read chapter 4 and I can answer questions on it"
  - 5:
    subject: Maths
    homeworks:
      - 1:
        title: Learn your 4 times table
        content: I learnt my 4 times table by heart
        help: Use flash cards with the answers on the back to help you learn
  - 6:
    subject: History
    homeworks:
      - 1:
        title: Gladiators
        content: I remember the vocabulary
        media: gladiators.jpg
  - 7:
    subject: Maths
    homeworks:
      - 1:
        title: Learn to tell the time
        content: I know how to tell the different times.
        media: time.jpg
  - 8:
    subject: Culture
    homeworks:
      - 1:
        title: Cinema
        content: I know who the Lumière brothers and I quote my favorite movie.
        media: cinema.jpg
  - 9:
    subject: Politics
    homeworks:
      - 1:
        title: Elections
        content: I know how the president is elected
        media: president.jpg
  - 10:
    subject: Mental maths
    homeworks:
      - 1:
        title: The 5 times table
        content: I know the 5 times table by heart
        help: Use flash cards with the answers on the back to help you learn
  - 11:
    subject: Sciences
    homeworks:
      - 1:
        title: The forest
        content: I know 3 trees and I recognise their leaves
        media: tree.jpg
  - 12:
    subject: Reading
    homeworks:
      - 1:
        title: Reading
        content: I read my chosen book and I took notes. I can answer the who, what, why questions.
  - 13:
    subject: French
    homeworks:
      - 1:
        title: Past tense
        content: I can conjugate the verbs in the past tense : manger - courir - entendre - mordre.
  - 14:
    subject: Grammar
    homeworks:
      - 1:
        title: Punctuation
        content: I know when to use full stops and commas.
  - 15:
    subject: Spelling
    homeworks:
      - 1:
        title: Spelling
        content: I learnt to spell 10 new words.
        media: newwords.jpg
  - 16:
    subject: Maths
    homeworks:
      - 1:
        title: Multiplication
        content: I know how to solve; 41x4 ; 55x72 ; 6x123
  - 17:
    subject: Spanish
    homeworks:
      - 1:
        title: introducing myself
        content: I can introduce myself in spanish.
  - 18:
    subject: History
    homeworks:
      - 1:
        title: Louis XIV
        content: I know who Louis XIV is and I understand the words in yellow.
        media: louisxiv.jpg
  - 19:
    subject: Geography
    homeworks:
      - 1:
        title: The world map
        content: I know the different continents.
        media: planisphere.jpg
  - 20:
    subject: Physics
    homeworks:
      - 1:
        title: Wind power
        content: I know how wind power is harvested. I prepared a short presentation to explain it
        media: wind.jpg

