liaisonBook:
  - 1:
    title: The class photo will be on Friday !
    content: "<p>Dear Parents,</p>  <p>The photo for class CE1 will be on Friday morning. Please bring your authorisation forms by Friday.&nbsp;</p>  <p>Cheese!</p>"
  - 2:
    title: Looking for parents to accompany us to the museum outing
    content: "<p>Dear parents,</p><p>We are looking for volunteers to accompany us to the museum on the 27th of April. We will go by bus to London to see the Natural History Museum</p><p>Thank you!</p>"
  - 3:
    title: Trip to the swimming pool
    content: "<p>Dear parents,</p><p>Every Tuesday we will go to the pool. Please make sure your child has; :</p><ul><li> a swimming costume</li><li>a towel</li><li>goggles</li><li>ua snack</li><li>a little bottle of water</li><li>shower gel</li></ul></p><p>Thank you!</p>"
  - 4:
    title: Beware of lice
    content: <p>Dear parents,attention! The lice are back. Please inspect your child's hair for any signs. </p> <p>Thank you for your attention!</p>
  - 5:
    title: Requests for the school fair
    content: <p>Dear parents,</p><p>As you know, the school fair is approaching. We are looking for volunteers to host their own stall, selling raffel tickets, food, toys etc. If you are intrested please get in touch!</p>
  - 6:
    title: Puppet Show
    content: <p>Dear parents,&nbsp;</p><p>The kids have the chance to see the Marion Nette pupper show on Tuesday morning. We will take lots of photos! We are looking for three volunteers to come with us. If you are intrested then please send a message via Beneylu School.</p><p>Thanks!</p>
