lunch:
  - 1:
    label: Taste Week
    description: It's the week of tasting new things!
    sections:
    menus:
      - 1:
        status: 1
        starter: Salmon
        main_course: Fish
        dessert: banana
        dairy: Yoghurt
        accompaniment: Pasta
        afternoon_snack: Biscuit
      - 2:
        status: 2
      - 3:
        status: 3
      - 4:
        status: 1
        full_menu: Pasta and tomato salad
      - 5:
        status: 1
        starter: Salad
        main_course: Meat
        dessert: Fruit
        dairy: Yoghurt
        accompaniment: Chips
        afternoon_snack: Cake
