message:
  - 1:
    from: pupil
    to: pupil
    title: Book exchange
    content: >
      <p>Can you lend me your book about horses, I'll lend you my book on volcanoes? !</p>

      <p>See you tomorrow.</p>
  - 2:
    from: pupil
    to: pupil
    title: Football at break tomorrow
    content: >
      <p>Lets play football at breaktime tomorroa! I can bring a ball. See you then!</p>
  - 3:
    from: pupil
    to: teacher
    title: I forgot my canteen card
    content: >
      <p>Hello, I forgot my canteen card today, how can I get a new one?!</p>
      <p>Lisa.</p>
  - 4:
    from: parent
    to: teacher
    title: Katie's glasses
    content: >
      <p>Hello,</p>
      <p>Katie left her glasses at home, I will bring then at lunch time<p>
      <p>Thank you</p>
  - 5:
    from: teacher
    to: parent
    title: Forgotten bag
    content: >
      <p style="text-align: justify;">Hello,</p>
      <p style="text-align: justify;">Your daughter left her bag in class today. I have put it in my classroom for safe keeping. she can pick it up tomorrow.</p>
      <p style="text-align: justify;">For the homework; she can find the documents online on Beneylu school</p>
      <p style="text-align: justify;">Have a good evening</p>
      <p style="text-align: justify;">See you tomorrow !</p>
  - 6:
    from: parent
    to: teacher
    title: Forgotten bag
    content: >
      <p>Bonsoir,</p>
      <p>Thank you for informing us! We have been searching everywhere</p>
      <p>Great, thank you for the homework files on Beneylu, it's very practical!!</p>
      <p>See you tomorrow.</p>
  - 7:
    from: teacher
    to: pupil
    title: I forgot my canteen card
    content: >
      <p>Hello,</p>
      <p>Seen as you have lost your card, we can make you a new one for tomorrow. Until then, we have a special one you can use ;-)&nbsp;</p>
      <p>See you later !</p>
  - 8:
    from: parent
    to: teacher
    title: Thank you!
    content: >
      <p>Hello,</p>
      <p>We wanted to thank you for the trip to the zoo, it was very well organised and the kids had a great time!!</p>
      <p>Thanks again.</p>
  - 9:
    from: pupil
    to: pupil
    title: Cinema on Saturday?
    content: >
      <p>Hi,</p>
      <p>Do you want to go to the cinema on Saturday afternoon? The new Finding Dory film is out. My mum said she can take us</p>
      <p>I hope you can come, bye</p>
  - 10:
    from: parent
    to: teacher
    title: Difficulties reading
    content: >
      <p>Good Evening,</p>
      <p>My son seems to be having some difficulty reading, have you noticed this in class? We are taking him to the opticians this week</p>
      <p>Thank you!</p>
  - 11:
    from: pupil
    to: pupil
    title: Brazillian bracelets
    content: >
      <p>Hi,</p>
      <p>I learned how to make these pretty bracelets this weekend. Tomorrow I will show you how. I can make you one if you like!</p>
      <p>See you !</p>
  - 12:
    from: parent
    to: teacher
    title: Birthday party
    content: >
      <p>Hello,</p>
      <p>It's my daughters birthday next week and I would like to make a cake to bring into class. Do any of the children have any allergies?</p>
      <p>Thank you.</p>
  - 13:
    from: pupil
    to: teacher
    title: Rubbish at maths
    content: >
      <p>Dear Mrs Brown,</p>
      <p>I am really stuck on the maths homework, could you please help me?</p>
      <p>Thank you</p>
      <p>See you tomorrow</p>
  - 14:
    from: parent
    to: pupil
    title: Library books
    content: >
      <p>Hi David</p>
      <p>You left your library books at home again, you need to bring them back tomorrow else they will be overdue! !</p>
      <p>See you after school.</p>
