minisite:
  - 1:
    banner: banner1.jpg
    presentation: We are proud to present our website! Discover our activities and the life of our primary school. We hope you enjoy it!
    home:
      title: Welcome
      content: >
        <p>Welcome to our primary school. We welcome all children from 4-12 years. The school is located just outside London so we make regular cultural visits, but we can also enjoy the sunny playground in the school and the vegetable garden!. Our school offers many activities including: swimming, choir, sports and music.</p>
      images:
        - home1.jpg
        - home2.jpg
        - home3.jpg
    actu:
      title: The news
      content:
        - 1:
          title: Puppet Show at school!
          content: >
            <p>On Wednesday the 29th April we are going to see a pupppet show.</p>
            <p>The children will be attending the show in the morning in our courtyard. The show has humour, songs and fantastic stories. There will also be musical instruments for the children to play.</p>
            <p>We look forward to it !</p>
          images:
            - puppet1.jpg
        - 2:
          title: Week Poetry
          content: >
            <p style="text-align: justify;">Poetry week will begin on the 28th March so get writing! We invite students, parents, teachers and everyone else to write a poem. At the end of the week the best poem will be chosen and displayed in the school.</p>
            <p style="text-align: justify;">Good luck to everyone.</p>
            <p style="text-align: center;"><strong>The Swing</strong></p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">How do you like to go up in a swing,></p>
            <p style="text-align: center;">Up in the air so blue?></p>
            <p style="text-align: center;">Oh, I do think it the pleasantest thing</p>
            <p style="text-align: center;">Ever a child can do!</p>
            <p style="text-align: center;">Up in the air and over the wall,</p>
            <p style="text-align: center;">Till I can see so wide,,</p>
            <p style="text-align: center;">River and trees and cattle and all</p>
            <p style="text-align: center;">Over the countryside--</p>
            <p style="text-align: center;">Till I look down on the garden green,</p>
            <p style="text-align: center;">Down on the roof so brown-- </p>
            <p style="text-align: center;">Up in the air I go flying again,</p>
            <p style="text-align: center;">Up in the air and down! /p>
            <p style="text-align: center;"><By Robert Louis Stevenson</em></p>
          images:
            - sun.jpg
        - 3:
          title: Saturdqy June 13th will be the school fair
          content: >
            <p>Come to the school fair! We have lots of fun games and prizes to win! There will be a treasure hunt, face painting and a bouncy castle! Let the party begin!</p>
          images:
            - fair.jpg
            - fair1.jpg
            - fair2.jpg
    pages:
      - 1:
        title: School Workshop
        content: >
          <h1 style="text-align: center;">The IT workshop will be held on Friday morning with Mrs Brown.</h1>
          <p style="text-align: justify;">Mrs Brown is responsible for the <strong> IT workshop</strong>. Everyweek the pupils get to progress their skills in IT to help in their transition to secondary school.</p>
          <p style="text-align: justify;">Every Tuesday after lunch Mrs Harlow hosts a <strong>dance workshop</strong>. The pupils work with ?rs Harlow to choreograph a routine to present at <strong>the end of year show</strong>.</p>
        images:
          - activity1.jpg
          - activity2.jpg
      - 2:
        title: Class Trips
        content: >
          <h1>The class trips</h1>
          <h1 style="text-align: center;">Out on the farm</h1>  <p>&nbsp;</p>  <p>On Tuesday P1 went to the farm to learn about the daily goings on. We got to see the cows being milked and even got a taste! We also got to see how cheese gets made.</p>  <p>It was great!</p>  <p>We are going to prepare a blog post on what we saw!.</p>
          <h1>Trip to Chambord Castle</h1>  <p style="text-align: justify;">The P3 class visited the Chambord Castle. They got to learn about the history of the area <a href="http://chambord.org/decouvrir-chambord/le-chateau/au-fil-de-lhistoire/" target="_blank">par ici</a> !</p>
        images2:
          - amboise.jpg
          - farm.jpg
          - farm1.jpg
