datas:
  - 1:
    first_name: Lisa
    last_name: Dunn
    gender: F
  - 2:
    first_name: Melissa
    last_name: NcCluskey
    gender: F
  - 3:
    first_name: Steven
    last_name: Allen
    gender: M
  - 4:
    first_name: Emma
    last_name: Gilchrist
    gender: F
  - 5:
    first_name: Benjamin
    last_name: Donald
    gender: M
  - 6:
    first_name: Claire
    last_name: Aitken
    gender: F
  - 7:
    first_name: Craig
    last_name: Scott
    gender: M
  - 8:
    first_name: Gordon
    last_name: Reid
    gender: M
  - 9:
    first_name: Ross
    last_name: Doherty
    gender: M
  - 10:
    first_name: Samantha
    last_name: Shields
    gender: F
  - 11:
    first_name: Darren
    last_name: Mundie
    gender: M
  - 12:
    first_name: Maria
    last_name: Hayworth
    gender: F
  - 13:
    first_name: Emilia
    last_name: White
    gender: F
  - 14:
    first_name: David
    last_name: Cowan
    gender: M
  - 15:
    first_name: Emily
    last_name: NcKay
    gender: F
  - 16:
    first_name: Louise
    last_name: Thomas
    gender: F
  - 17:
    first_name: Samuel
    last_name: Brown
    gender: M
  - 18:
    first_name: Charlotte
    last_name: Healey
    gender: F
  - 19:
    first_name: Richard
    last_name: Matthews
    gender: M
  - 20:
    first_name: Lara
    last_name: Taylor
    gender: F
  - 21:
    first_name: Jamie
    last_name: Hughes
    gender: M
  - 22:
    first_name: Idriss
    last_name: Tahney
    gender: M
  - 23:
    first_name: Sabrina
    last_name: Craig
    gender: F
  - 24:
    first_name: Georgia
    last_name: Bretman
    gender: F
  - 25:
    first_name: Ahmed
    last_name: Alderson
    gender: M
job:
  - Vet
  - Fighter Pilot
  - Fireman
  - Policeman
  - Footballer
  - Engineer
  - Lawyer
  - Doctor
  - Cardiologist
  - Community manager
  - Professor
  - Teacher
  - Animator
  - Lifeguard
  - Historian
  - TV presenter
  - Maths teacher
  - Stuntman
  - Nurse
  - Judge
  - Athlete
  - Writer
  - Explorer
  - Wildlife photographer
  - Pediatrician
presentation:
  - I like our teacher and going to school (especially when we can do sport)
  - I am 8 years old, i'm quite smart and i love gardening
  - Hi! I'm 8 and i love sports.
  - I love going to the library and hearing scary stories.
  - I'm 7 years old and i love to sign! I'm in the choir at school
  - I like music and dancing, too, because it puts me in a good mood. I am 8 years old!!
  - Hello, I'm super friendly and I love animals. Especially dogs and horses.
  - Hello everyone. I'm 7 years old and I like going to school, we do a lot of activities.
  - I like cars, fire trucks and planes too.
  - Hello! I am 6, i love to eat sweets but i'm only allowed a few or else I will get cavities
  - Hello! I am 8 years old, I like playing outside, running and making cakes with my sister.
  - I'm nearly 8 years old. I like doing geography and maths in school
  - Hello! I love going on adventures
  - Hello. I like going to the sea and collect shells. I like the manual work in the classroom.
  - Hi! I am 7 years old and i like poetry and travel.
  - Hello, I like going to school because I can see my friends and we have fun, especially at break time.
  - I'm 8 years old qnd i like animals, i have a cat called Poppy
  - Hello everybody! I am 8 years old and I love to go to the cinema.
  - Hello, I'm 7 years old and I can do magic tricks with cards. This is my grandfather who taught them to me.
  - Hello! I would walk on the moon one day, this is my dream! And I like history.
  - Hello, I am 8 years old and I like to write stories with heroes and adventures.
  - Hi! I like to cook, I can already make cakes and pancakes. It's easy and good.
  - Hello! I traveled to France with my family this summer and I know a few words in French. I like surfing too, but it's hard.
  - Hello everyone! my favourite class is art, I like to draw.

like:
  - Songs
  - Hamburgers
  - Going to the pool
  - Scary stories
  - To go fishing with my grandad
  - Pasta
  - Playing with my cat
  - Vanilla ice-cream
  - Animals
  - Pizzas
  - Gardening
  - My cat
  - When it's nice and hot
  - Chocolate
  - Art
  - Singing
  - Drinking orange juice
  - Maths
  - Poemes
  - Ketchup
  - Cute cats
  - dogs
  - Kittens
  - Riddles
  - Beneylu School
  - To go on the Internet
  - Eating chocolate
  - Video games
  - Painting
  - cars
  - Sport
  - Reading
  - Star Wars
  - Cartoons
  - Cycling
  - Skiing
  - My familly
  - Summer holidays
  - Sweets
  - Birthdays
  - Parties
  - Horse riding
  - Flamenco dancing
  - To win
  - Memory games
  - Magic
  - Riddles
  - The beach
  - Funny stories
  - Roller blading
dislike:
  - Bad marks
  - Doing my homework
  - The rain
  - Broccoli
  - Arguments
  - The end of holidays
  - Injustices
  - Green beans
  - Maths
  - Waiting for christmas
  - The jokes I don't understand
  - Bad people
  - Getting told off
  - Vegetables
  - Mustard
  - Tomatoes
  - Teenage Mutant Ninja Turtles
  - Bed time
  - Chips
  - Red
  - Rap
  - Lies
  - People being mean
  - Being angry
  - Getting stains on my clothes
  - Bad dogs
  - Being bored
  - Homework on holidays
  - Grammar
  - Spelling
  - Holidays
  - The cafeteria
  - The cold
  - Sunburn
  - Thieves
  - Orange
  - Meat
  - To be in the car
  - English
  - Being ill
  - Being late for School
  - Falling
  - Fizzy soda
  - Cats that scrath
  - Going to the races
  - Losing my things
  - Fruit
  - The dentist
  - Waiting
  - Putting my head under water

status:
  - 1:
    text: We won the football yesterday! Roll on the next match!
    comments:
    - Congratulations! You will win again tomorrow
    - Lucky you had a good goalkeeper
  - 2:
    text: What is green and goes up and down? A pea in a lift!
    comments:
    - Hahaha
    - Good joke!
  - 3:
    text: Roll on the holidays!
    comments:
    - It's nearly there!
    - Me too!
    image: fleur.jpg
  - 4:
    text: Today I am super happy because it's my birthday! We are going to eat a cake :-)
    comments:
    - Happy Birthday!
    - Hooray
  - 5:
    text: Tomorrow we are going to the pool, I've decided i'm going to jump off the diving board
    comments:
    - Good luck!
    - Bravo.
    - Very good
  - 6:
    text: I'm watching spongebob square pants its super funny!
    comments:
    - I'm watching it with my big brother
    - Lucky!
    - I don't really like it.
  - 7:
    text: I've got hay fever because of the pollen!
    comments:
    - Oh no! get better soon.
    - Me too, good luck!!
  - 8:
    text: I've finished the homework. Maths was hard but I think i've succeeded.
    comments:
    - I'm not so sure...
    - I haven't started yet!
  - 9:
    text: I was at the skate park yesterday with my brother. There was lots of other kids to play with, very cool!
    comments:
    - I'll go with you the next time.
    - Me too, I went but in the late afternoon
  - 10:
    text: Next weekend my parents are taking me to the mountains, I'll bring in some cheese to school.
    comments:
    - Super!
    - Thank you! And take lots of nice pictures
  - 11:
    text: Who is going on holiday this summer?
    comments:
    - Me! To France, like last year.
    - Me!
    - Not me!
  - 12:
    text: We prepared for the games fair
    comments:
    - We made drawings and paper decorations
    - I'm looking forward to being there!
  - 13:
    text: I finished reading my library book! It was great!
    comments:
    - What book was it?.
    - I would like to read a story like Harry Potter
  - 14:
    text: Yesterday I watched a video about kangaroos, they are cute
    comments:
    - They are my favourite animals.
  - 15:
    text: Do you know any riddles or jokes?
    comments:
    - Two snails go to the beach. They cross a slug and turn to eachother and say "we are on a nudist beach!"
    - Ah ah ah ! Very good
  - 16:
    text: Tomorrow at break time lets play chase!
    comments:
    - That's a good idea!
    - Cool!
  - 17:
    text: Do you know about the troglodytes?
    comments:
    - It's a house made of rocks, i think?
    - Like for dwarves?
  - 18:
    text: I like listening to music and I like singing. I really like Adelle
    comments:
    - Me too! She is really good.
    - Yeah! I love to sing!
  - 19:
    text: My mum taught me how to make paella, its a spanish dish and it's really tasty.
    comments:
    - Yum !
    - I've tried it before, it's really good.
    - I don't like it.
  - 20:
    text: Are you listening to the radio? There is a really good concert on
    comments:
    - I want to hear!
  - 21:
    text: Who do you think will win the match tomorrow?
    comments:
    - I think Germany!
    - England!
  - 22:
    text: I'm in a good mood, it's nice!
    comments:
    - Enjoy the sun
    - Super!
  - 23:
    text: This weekend I bought a gold fish. His name is Borris
    comments:
    - Haha that's a funny name!
    - My cat is called Borris!
  - 24:
    text: I fell over and hurt my leg yesterday
    comments:
    - Ah ouch!
    - I bet that hurt
  - 25:
    text: Tomorrow in the canteen there is spaghetti bolognese, its my favourite!
    comments:
    - Me too, I love it!
