name:
  - Hermitage Primary School
  - Rhu Primary School
uai:
  - 123456X
  - 654321X
  - 789456X
  - 456321X
address:
  - 1 School Road
  - 3 John Street
  - 18 Buchanan Street
  - 14 High Street
  - 55 Sinclair Street
zipcode:
  - G849JJ
  - GB 828
  - G1 80U
  - CR0 3RL
  - E16 3GZ
city:
  - Glasgow
  - Liverpool
  - Edinburgh
  - London
  - Manchester
  - Leeds
  - Inverness
home_message:
  - Welcome to your school space
  - We would like to welcome you to your school's digital workspace
  - Discover your messages in the blog