datas:
  - 1:
    first_name: Douglas
    last_name: Morgan
    gender: M
  - 2:
    first_name: Anne
    last_name: Trevelyan
    gender: F
job:
  - School teacher
  - School teacher
presentation:
  - Welcome to my profile
  - Dear students, you can contact me via mail
like:
  - My pupils
  - History
  - Geography
  - Maths
  - Peaches
dislike:
  - Bad grades
  - Football
  - Basketball
  - Surfing
  - Cooking
  - Doing dishes
status:
  - 1:
    text: Post a comment
    comments:
    - Here is a comment!
    - Hello!
    - Too easy!
  - 2:
    text: I went to the countryside near my house this weekend, beautiful!!
    comments:
    - Lovely photo
    - Me too, i love the forest!
