event:
  - 1:
    title: Biblioteca
    content: No olviden regresar los libros a la biblioteca ;-)
    start: 14
    end: 16
  - 2:
    title: Deportes
    content: Esta semana vamos a practicar futbol.
    start: 10
    end: 12
  - 3:
    title: Piscina
    content: No olviden sus gorras de baño.
    start: 9
    end: 11
  - 4:
    title: Música
    content: Canto en coro
    start: 10
    end: 11
  - 5:
    title: Jardinería
    content: Vamos a plantar zanahorias esta semana.
    start: 13
    end: 15
  - 6:
    title: Fiesta de cumpleaños
    content: ¡Vamos a comer pastel de chocolate!
    start: 15
    end: 16
  - 7:
    title: Correspondencia escolar con nuestros amigos ingléses
    content: Esta semana vamos a presentarnos.
    start: 9
    end: 11
  - 8:
    title: Visita al zoológico
    content: No olviden sus cámaras fotográficas.
    start: 15
    end: 16
  - 9:
    title: Preparación de la kermesse
    content: Taller de decoración en papel.
    start: 10
    end: 12
  - 10:
    title: Campeonato de futbol
    content: Competición mixta.
    start: 16
    end: 18
  - 11:
    title: Iniciación a la danza africana
    content: Traigan ropa cómoda.
    start: 9
    end: 12
  - 12:
    title: Espectáculo de marionetas
    content: Con la compañía de teatro Entre hilos
    start: 14
    end: 16
  - 13:
    title: Deportes
    content: Esta semana vamos a practicar karate.
    start: 10
    end: 12
  - 14:
    title: Taller de educación vial.
    content: Se llevará a cabo en eI patio, con bicicletas.
    start: 14
    end: 15
  - 15:
    title: Taller de periodismo
    content: Voluntarios para el periódico escolar.
    start: 11
    end: 12
  - 16:
    title: Taller de efectos de sonido para películas
    content: Sobre una película de Disney.
    start: 17
    end: 18
  - 17:
    title: Concurso de ortografía
    content: Dictado de 100 palabras.
    start: 8
    end: 10
  - 18:
    title: Cuentos
    content: Con las bibliotecarias.
    start: 14
    end: 16
  - 19:
    title: Jardinería
    content: Esta semana vamos a deshierbar el huerto.
    start: 13
    end: 15
  - 20:
    title: Salida al bosque
    content: Vamos a observar los diferentes tipos de árboles.
    start: 10
    end: 12
  - 21:
    title: Basketball
    content: ¡Que el mejor gane!
    start: 14
    end: 16
  - 22:
    title: Cinema
    content: Vamos a ver La guerra de los botones
    start: 13
    end: 16
  - 23:
    title: Piscina
    content: Vamos a aprender a meter la cabeza bajo el agua.
    start: 9
    end: 11
  - 24:
    title: El circo
    content: Aprenderamos un truco de magia
    start: 8
    end: 10
  - 25:
    title: Cocina
    content: Vamos a preparar flan napolitano.
    start: 10
    end: 12
  - 26:
    title: Taller digital
    content: Vamos a leer utilizando las tablets.
    start: 9
    end: 10
  - 27:
    title: Música
    content: Vamos a aprender a tocar la flauta.
    start: 10
    end: 11
  - 28:
    title: Computación
    content: Redacción en el blog de Beneylu School.
    start: 14
    end: 16
  - 29:
    title: Rally de lectura
    content: Respondemos a las preguntas.
    start: 9
    end: 10
  - 30:
    title: Artes plásticas
    content: Vamos a aprender a pintar con acuarelas.
    start: 13
    end: 15