name:
  - 1ero A
  - 1ero B  
  - 2ndo A
  - 2ndo B
  - 3ero A
  - 3ero B
  - 4to A
  - 4to B
  - 5to A
  - 5to B
  - 6to A
  - 6to B
home_message:
  - Bienvenidos a su aula digital
  - Les damos la bienvenida a su espacio clase en la plataforma Beneylu School
  - Bonjour, Hello, Hallo, Buenos Dias, namaste, buongiorno...