gps:
  - 1:
    title: Palacios del Mundo
    places:
      - 1:
        title: Palacio de Versalles
        address: Palacio de Versalles
      - 2:
        title: Palacio de Buckingham
        address: Palacio de Buckingham
      - 3:
        title: Palacio real de Madrid
        address: Calle de Bailén, 3, 28013 Madrid, España
  - 2:
    title: Pueblos mágicos de México
    places:
      - 1:
        title: San Cristobal de las Casas
        address: San Cristobal de las Casas, Chiapas, México
      - 2:
        title: Dolores Hidalgo
        address: Dolores Hidalgo, Guanajuato, México
      - 3:
        title: Papantla
        address: Papantla, Veracruz, México
  - 3:
    title: Monumentos famosos
    places:
      - 1:
        title: Arco del Triunfo
        address: Place Charles de Gaulle, 75008 Paris
      - 2:
        title: Central Park
        address: Central Park Manhattan New York
      - 3:
        title: La Sagrada Familia
        address: Sagrada Familia
  - 4:
    title: Sitios turísticos
    places:
      - 1:
        title: El Taj Mahal
        address: Taj Mahal
      - 2:
        title: Las cascadas del Niagara
        address: cascadas del niagara
      - 3:
        title: Stonehenge
        address: Stonehenge
  - 5:
    title: Lugares increíbles
    places:
      - 1:
        title: El Monte Rushmore
        address: 13000 S Dakota 244, Keystone, SD 57751, Estados Unidos
      - 2:
        title: El Monte Saint-Michel
        address: Monte Saint-Michel
      - 3:
        title: El desierto del Sahara
        address: Desierto del Sahara