homework:
  - 1:
    subject: Geografía
    homeworks:
      - 1:
        title: Aprendo 5 países de Europa
        content: Investigar y escribir sobre 5 países de Europa. Mencionar: modo de vida, costumbres, clima, cultura,...
        media: europa.jpg
  - 2:
    subject: ciencias naturales
    homeworks:
      - 1:
        title: Animales vertebrados e invertebrados
        content: Aprender las diferencias entre los animales vertebrados e invertebrados.
        media: animales.pdf
      - 2:
        title: Animales de sangre fría
        content: Dibujar tres ejemplos de animales de sangre fría y el lugar en donde habitan.
        media: animales.pdf
  - 3:
    subject: Francés
    homeworks:
      - 1:
        title: Aprender la conjugación en pasado de los verbo aimer, chanter, danser, aller
        content: "<p>Conozco la conjugación de los verbos en pasado.</p>               <p>Escribo 4 oraciones utilizando cada verbo en pasado.</p>               <p>Dibujo la representación de cada oración.</p>"
        help: Aprendemos la utilización de los auxiliares "avoir" o "être".
  - 4:
    subject: Lectura
    homeworks:
      - 1:
        title: Leer el capítulo 4 del libro de lectura
        content: "Leo el capítulo 4 y soy capaz de contestar a las preguntas ¿quién? ¿qué? ¿cuando? ¿donde? ¿cómo?"
  - 5:
    subject: Matemáticas
    homeworks:
      - 1:
        title: Tabla del 4
        content: Aprendo de memoria la tabla de multiplicar del 4.
        help: Haz tarjetas para ayudarte: de un lado escribes 4x1, 4x2.. y del otro lado la respuestas. Estas tarjetas te servirán para entrenarte. ¡No se vale hacer trampa!.
  - 6:
    subject: Historia
    homeworks:
      - 1:
        title: La revolución industrial
        content: Leo y hago un resumen sobre el tema.
        media: revolucion_industrial.pdf
  - 7:
    subject: Matemáticas
    homeworks:
      - 1:
        title: Leer la hora
        content: Puedo identificar la hora correcta en los diferentes relojes.
        media: la_hora.jpg
  - 8:
    subject: Español
    homeworks:
      - 1:
        title: Los cuentos
        content: Aprendo las partes del cuento y escribo un cuento corto.
        media: cuento.jpg
  - 9:
    subject: Educación cívica
    homeworks:
      - 1:
        title: Elecciones
        content: Investigo cómo es elegido el presidente de la república. Escribo un resumen.
  - 10:
    subject: Matemáticas
    homeworks:
      - 1:
        title: Tabla del 5
        content: Aprendo de memoria la tabla de multiplicar del 5.
        help: Haz tarjetas para ayudarte: de un lado escribes 5x1, 5x2.. y del otro lado la respuestas. Estas tarjetas te servirán para entrenarte. ¡No se vale hacer trampa!.
  - 11:
    subject: Ciencias naturales
    homeworks:
      - 1:
        title: El reciclaje
        content: Aprendo como separar la basura reciclable y no reciclable.
        media: reciclaje.png
  - 12:
    subject: Rally de lectura
    homeworks:
      - 1:
        title: Lectura
        content: Leo un libro que he escogido y tomo notas para poder contestar a las preguntas: ¿quién? ¿qué? ¿cuando? ¿donde? ¿cómo?. Presento mi libro a mis compañeros.
  - 13:
    subject: Francés
    homeworks:
      - 1:
        title: Le passé composé
        content: Sé conjugar los verbos en passé composé y sé a que sirve cada tiempo. Conjuga los verbos: manger - s'évanouir - courir - entendre - mordre.
        media: passe.pdf
  - 14:
    subject: Dictado
    homeworks:
      - 1:
        title: Hacer un dictado con las palabras aprendidas la semana pasada
        content: Le pido a mi mamá o a mi papá que me ayude.
  - 15:
    subject: Ortografía
    homeworks:
      - 1:
        title: Uso de ll e y
        content: Sé cuando utilizar ll e y.
        media: Ortografia_4.pdf
  - 16:
    subject: Calculo
    homeworks:
      - 1:
        title: Multiplicación
        content: Resuelvo las siguientes multiplicaciones 41x4 ; 55x72 ; 6x123
  - 17:
    subject: Inglés
    homeworks:
      - 1:
        title: Me presento
        content: Me presento en inglés.
  - 18:
    subject: Inglés
    homeworks:
      - 1:
        title: Mi familia
        content: Aprendo el vocabulario de la familia y escribo los nombres de mi familia en el árbol genealógico.
        media: family_tree.jpg
  - 19:
    subject: Geografía
    homeworks:
      - 1:
        title: El mapa del mundo
        content: Se ubicar los continentes y los océanos.
        media: mapa.jpg
  - 20:
    subject: Ciencias naturales
    homeworks:
      - 1:
        title: Las estaciones del año
        content: Sé identificar las estaciones del año. Contesto las preguntas del cuestionario
        media: estaciones.pdf

