liaisonBook:
  - 1:
    title: La foto de grupo sera tomada el próximo viernes
    content: "<p>Queridos papás,</p>  <p>La foto del grupo de 1ero sera tomada el próximo viernes en la mañana, en el auditorio de la escuela. No olviden enviar sus autorizaciones antes del jueves.&nbsp;</p>  <p>¡Sonrian!</p>"
  - 2:
    title: Papás voluntarios para la visita al museo
    content: "<p>Queridos papás,</p><p>Necesitamos algunas papás voluntarios para acompañar a nuestros alumnos durante la visita al museo el próximo 27 de Abril. Iremos en el autobus escolar hasta la ciudad de México para descubrir el Museo de Historia. Necesitamos la ayuda de 3 padres de familia.</p><p>Gracias.</p>"
  - 3:
    title: Piscina
    content: "<p>Queridos papás,</p><p>Todos los martes, sus hijos van a la pisicina. Por favor, prepare la mochila de su hijo con:/p><ul><li>una toalla</li><li>un gorro de baño</li><li>un traje de baño</li><li>un paquete de galletas o una fruta</li><li>una botella de agua pequeña</li><li>jabón</li></ul></p><p>Gracias por su atención</p>"
  - 4:
    title: Atención a los piojos
    content: <p>Queridos papás, atención, ¡Los piojos están de regreso! Revise bien a sus hijos y no olvide los gestos simples: no prestar gorrar, ni cepillos para el cabello, etc...&nbsp;</p> <p>Gracias por su atención</p>
  - 5:
    title: Donación de regalos para la kermesse de la escuela
    content: <p>Queridos papás,</p><p>Como ustedes lo saben, organizamos una kermesse para cerrar el año escolar. Buscamos personas que puedan donar regalos para la lotería y tombola. Si usted trabaja en una empresa y puede proponer este tipo de donaciones, contactenos via la mensajería de Beneylu School.</p><p>Gracias por su generosidad.</p>
  - 6:
    title: Espectáculo
    content: <p>Queridos papás,&nbsp;</p><p>Los niños tendrán la oportunidad de ver un espectáculo de marionetas de la compañia En el Hilo Rojo, el próximo martes. ¡tomaremos muchas fotos! Buscamos un papá o una mamá para ayudarnos durante este evento. Los voluntarios pueden escribirnos directamente vía la mensajería de Beneylu School.</p><p>Gracias</p>