lunch:
  - 1:
    label: Semana de los sabores
    description: ¡Es la semana de los sabores!
    sections:
    menus:
      - 1:
        status: 1
        starter: Salmón
        main_course: Pescado
        dessert: Plátano
        dairy: Yogurt
        accompaniment: Pasta
        afternoon_snack: Galletas de avena
      - 2:
        status: 2
      - 3:
        status: 3
      - 4:
        status: 1
        full_menu: Ensalada de tomates y pepino
      - 5:
        status: 1
        starter: Ensalada
        main_course: Carne
        dessert: Fruta
        dairy: Yogurt
        accompaniment: Papas a la francesa
        afternoon_snack: Pastel de chocolate
