message:
  - 1:
    from: pupil
    to: pupil
    title: Intercambio de libros
    content: >
      <p>¿Podrías prestarme tu libro sobre los caballos? Yo puedo prestar mi libro sobre los volcanes, si quieres. También tengo otro lugar que cuenta una historia verdadera.</p>
      <p>Hasta mañana</p>
  - 2:
    from: pupil
    to: pupil
    title: Partido de futbol durante el recreo
    content: >
      <p>Estamos organizando un partido de futbol con los de tercero, durante el recreo. No olvides traer tus tenis y mucha energía. ¡Vamos a ganar!</p>
  - 3:
    from: pupil
    to: teacher
    title: Perdí mi cuaderno de español
    content: >
      <p>Hola maestra, perdí mi cuaderno de español, o a lo mejor lo dejé en el salón. ¿No lo ha visto? Gracias</p>
      <p>Elisa.</p>
  - 4:
    from: parent
    to: teacher
    title: Los lentes de nuestro hijo
    content: >
      <p>Buenas tardes,</p>
      <p>Nuestro hijo tendrá que usar lentes a partir del próximo mes. ¿Podría por favor informarnos si él ve mejor el pizarrón?<p>
      <p>Gracias</p>
  - 5:
    from: teacher
    to: parent
    title: Olvido de la mochila
    content: >
      <p style="text-align: justify;">Buenos días Sra. Lilia,</p>
      <p style="text-align: justify;">Su hija ha olvidado su mochile en el salón. No se preocupe, la he guardado y la puede recuperar desde mañana. Muchas gracias por su atención.</p>
      <p style="text-align: justify;">Por la tarea, ella tiene que leer y escuchar el documento sobre la revolución industrail y escribir un resumen; después, cargar su resumen en la mediateca.</p>
      <p style="text-align: justify;">Que tenga una excelente tarde.</p>
      <p style="text-align: justify;">Hasta mañana</p>
  - 6:
    from: parent
    to: teacher
    title: Olvido de la mochila
    content: >
      <p>Buenas tardes,</p>
      <p>Muchas gracias por avisarnos. Habiamos buscando por todos lados sin éxito.. Estábamos preocupados...;-)</p>
      <p>Entendido por las tareas. La plataforma es muy práctica.</p>
      <p>Hasta mañana y muchas gracias de nuevo.</p>
  - 7:
    from: teacher
    to: pupil
    title: Perdí mi cuaderno de español
    content: >
      <p>Buenos días,</p>
      <p>Encontré tu cuaderno de español, tirado en el salón. Me imagino que se te ha de haber caido de la mochila. Aquí te lo guardo para mañana ;-)&nbsp;</p>
      <p>Saludos,</p>
  - 8:
    from: parent
    to: teacher
    title: ¡Gracias!
    content: >
      <p>Querida maestra,</p>
      <p>queremos agradecerle por la organización de la visita al zoológico. Nuestros hijos estuvieron muy contentos. No han dejado de hablar de los animales que vieron durante la visita. Nos han hecho unos dibujos muy lindos con leones y jirafas.</p>
      <p>Muchas gracias y saludos.</p>
  - 9:
    from: pupil
    to: pupil
    title: Película en el cine el próximo sábado
    content: >
      <p>Hola,</p>
      <p>Me gustaría ir al cine el próximo sábado en la tarde. Mi mamá va a ir conmigo. ¿Quieres venir con nosotros? Pídele permiso a tus papás. Podemos ir a recogerte a tu casa y te llevamos de regreso.</p>
      <p>Espero que puedas venir.</p>
      <p>Adios</p>
  - 10:
    from: parent
    to: teacher
    title: Dificultades de lectura
    content: >
      <p>Buenas tardes,</p>
      <p>Nuestro hijo esta yendo al ortofonista desde hace dos meses y parece ser que está progresando. Gracias por habernos ayudado a encontrar una solución para ayudarlo, está encontrando de nuevo el gusto a la lectura. ¿Tendrá algún libro para él que nos pueda recomendar?</p>
      <p>Gracias</p>
      <p>Hasta pronto</p>
  - 11:
    from: pupil
    to: pupil
    title: Pulseras con hilo
    content: >
      <p>Hola,</p>
      <p>Mi tía me enseñó a hacer pulseras con hilo. Mañana te enseño el que hize con ella. También voy a llevarhilos de colores, para que podamos hacer algunas. No está dificil.&nbsp;</p>
      <p>¡Besos!</p>
  - 12:
    from: teacher
    to: pupil
    title: Tareas atrasadas
    content: >
      <p>Hola,</p>
      <p>Estuviste enferma ayer, espeor que hoy estes mejor. Hemos pensando mucho en ti y esperamos que regreses pronto a clases.</p>
      <p>Para las tareas atrasadas, puedes encontrar toda la información en la carpeta de la clase en la mediateca de Beneylu School. Ahí puse algunos documentos para ayudarte ;-)</p>
      <p>Escríbeme si tienes alguna pregunta.</p>
      <p>Recuperate pronto.</p>
      <p>Saludos,</p>
  - 13:
    from: parent
    to: teacher
    title: Pastel de cumpleaños
    content: >
      <p>Buenos días,</p>
      <p>Mi hija cumple años la próxima semana. Me gustaría que pudiera compartir este momento con sus amigos de la escuela. Estoy pensando en llevar un pastel y algunos dulce. ¿Sabe si alguno de los niños es alérgico al gluten?</p>
      <p>Gracias.</p>
      <p>Hasta pronto.</p>
  - 14:
    from: pupil
    to: teacher
    title: Las matemáticas
    content: >
      <p>Maestra,</p>
      <p>Creo que me fué muy mal el exámen de matemáticas. No pude hacer el ejercicio de repaso. Creo que soy muy malo para las matemáticas, ¿cómo puedo hacerle para progresar y no tener malas calificaciones?</p>
      <p>Gracias por su ayuda.</p>
      <p>Hasta mañana.</p>
  - 15:
    from: parent
    to: pupil
    title: Libros de la biblioteca
    content: >
      <p>Hijita,</p>
      <p>Los libros que te prestaron en la biblioteca se quedaron en la casa de tu abuelita. Te los traigo mañana, para que los regreses mañana</p>
      <p>Besos</p>
