minisite:
  - 1:
    banner: banner1.jpg
    presentation: Nuestra escuela esta orgullosa de presentarles nuestro nuevo sitio internet. Vengan a descubrir las actividades y la vida escolar de nuestra escuela primaria. ¡Bienvenidos!
    home:
      title: Bienvenidos
      content: >
        <p>Bienvenidos a la escuela primaria. Bienvenue à l'école primaire. Aceptamos niños y niñas de 6 a 11 años. La escuela esta situada en el Edo. de México, cerca del Distrito Federal. Debido a la cercanía con la capital, podemos organizar viajes culturales.</p>
        <p>Nuestra escuela propone diferentes activiades: música, piscina, coro, deportes, jardinería.</p>
      images:
        - home1.jpg
        - home2.jpg
        - home3.jpg
    actu:
      title: Las actualidades
      content:
        - 1:
          title: ¡Espectáculo de marionetas en la escuela!
          content: >
            <p>El próximo miércoles 29 de Abril tendremos un espectáculo de marionetas con la compañía Entre hilos rojos.</p>
            <p>Los alumnos asistirán al espectáculo en la mañana. Incluidos en el programa: humor, canciones e historias fantásticas... La compañía Entre hilos rojos traerá algunos instrumentos musicales para que los alumnos participen al ritmo de: triángulos, timbales, maracas...</p>
            <p>¡Esperamos que se diviertan!</p>
          images:
            - puppet.jpg
        - 2:
          title: Semana de la poesía
          content: >
            <p style="text-align: justify;">La <strong>edición 28 de la semana de la poesía</strong> sera inaugurada el próximo 13 de Marzo. ¡Vamos a escribir!Invitamos a todos los alumnos, a los padres de familia, maestros y todos aquellos que quieran, a escribir un poema el cual deberá ser depositado en el buzón de la escuela (dentro de un sobre). El poema más bonito será impreso y publicado en toda la escuela.</p>
            <p style="text-align: justify;">Suerte a todos.</p>
            <p style="text-align: center;"><strong>Infancia</strong></p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">Infancia, valle ameno,</p>
            <p style="text-align: center;">de calma y de frescura bendecida</p>
            <p style="text-align: center;">donde es suave el rayo</p>
            <p style="text-align: center;">del sol que abraza el resto de la vida.</p>
            <p style="text-align: center;">¡Cómo es de santa tu inocencia pura,</p>
            <p style="text-align: center;">cómo tus breves dichas transitorias</p>
            <p style="text-align: center;">cómo es de dulce en horas de amargura</p>
            <p style="text-align: center;">dirigir al pasado la mirada</p>
            <p style="text-align: center;">y evocar tus memorias!</p>
            <p style="text-align: center;"><em>José Asunción Silva, Poemas del Alma</em></p>
          images:
            - sun.jpg
        - 3:
          title: Kermesse de la Escuela: sábado 13 de Junio
          content: >
            <p>No olviden de asistir a la kermesse de la escuela. Habrán muchos juegos y premios para los ganadores.</p>  <p>Entre otras cosas:</p>  <p>una tombola</p>  <p>una búsqueda del tesoro en el patio de la escuela</p>  <p>un stand de pesca de patitos</p>  <p>un espectáculo de danza realizado por el grupo de 5to...</p>  <p>¡Que comienza la fiesta!</p>
          images:
            - kermesse1.jpg
            - kermesse2.jpg
            - kermesse2.jpg
    pages:
      - 1:
        title: Talleres de la escuela
        content: >
          <h1 style="text-align: center;">Taller de computación con los alumnos de 6to con la maestra Rosita</h1>
          <p style="text-align: justify;">La maestra Rosita es la responsable del <strong>taller de computación de 6to año</strong>. Cada semana, los alumnos progresan en informática (tratamiento de textos, búsqueda en internet...) lo cual les ayudará al momento de pasar a la secundaria. La maestra Rosita ha creado un blog para animar el taller de computación. Cada semana encontrarán un artículo o video de la clase.<img title="Sonrisa" src="https://beneylu.com/ent/bundles/stfalcontinymce/vendor/tiny_mce/plugins/emotions/img/smiley-sealed.gif" alt="Sonrisa" border="0"></p>
          <h1 style="text-align: center;">Taller de danza con los alumnos de 3ero con el maestro Carlos</h1>
          <p style="text-align: justify;">Cada martes después del desayuno, el maestro Carlos lleva a los alumnos de 3ero al auditorio de la escuela para <strong>el taller de danza</strong>. Los alumnos trabajan sobre dos coreografías para el <strong>espectáculo de fin de año</strong>. Los alumnos de 5to. preparan la decoración y organizan el espactáculo.&nbsp;</p>
        images:
          - activite1.jpg
          - activite2.jpg
      - 2:
        title: Salidas escolares
        content: >
          <h1>Las salidas escolares</h1>
          <h1 style="text-align: center;">Visita a una granja con los alumnos de 2ndo.</h1>  <p>&nbsp;</p>  <p>El martes pasado, los alumnos de 2ndo. visitaron una granja para descubrir los animales que viven ahí y el funcionamiento de una granja lechera. Después de la visita, hemos probado la leche fresca. También vimos como se fabrica el queso.</p>  <p>¡Estuvo genial!</p>  <p>Estamos preparando una presentación que vamos a publicar en el blog en los próximos días.</p>
          <h1>visita al palacio de los reyes</h1>  <p style="text-align: justify;">Los alumnos de 4to. visitaron el palacio de los reyes, el lunes pasado. Habían estudiado junto con su maestro sobre la monarquía.</p>
        images2:
          - amboise.jpg
          - ferme1.jpg
          - ferme2.jpg
