datas:
  - 1:
    first_name: Elisa
    last_name: Martínez
    gender: F
  - 2:
    first_name: Arturo
    last_name: Correa
    gender: M
  - 3:
    first_name: Florencia
    last_name: Blanco
    gender: F
  - 4:
    first_name: Astrid
    last_name: Montes
    gender: F
  - 5:
    first_name: Benjamin
    last_name: Benitez
    gender: M
  - 6:
    first_name: Clara
    last_name: Fernández
    gender: F
  - 7:
    first_name: Eric
    last_name: Gutierrez
    gender: M
  - 8:
    first_name: Federico
    last_name: García
    gender: M
  - 9:
    first_name: Julio
    last_name: Sierra
    gender: M
  - 10:
    first_name: Lucila
    last_name: Figaredo
    gender: F
  - 11:
    first_name: Marcos
    last_name: Durán
    gender: M
  - 12:
    first_name: Maria
    last_name: Valencia
    gender: F
  - 13:
    first_name: Marion
    last_name: Casian
    gender: F
  - 14:
    first_name: Carlos
    last_name: Rodríguez
    gender: M
  - 15:
    first_name: Sarah
    last_name: Andrade
    gender: F
  - 16:
    first_name: Sofia
    last_name: Cardenas
    gender: F
  - 17:
    first_name: Samuel
    last_name: Brigada
    gender: M
  - 18:
    first_name: Carlota
    last_name: Hortega
    gender: F
  - 19:
    first_name: Rafael
    last_name: Viveros
    gender: M
  - 20:
    first_name: Rebeca
    last_name: Sanchez
    gender: F
  - 21:
    first_name: Pablo
    last_name: Reynosa
    gender: M
  - 22:
    first_name: Yuko
    last_name: Saito
    gender: F
  - 23:
    first_name: Felipe
    last_name: Gomez
    gender: M
  - 24:
    first_name: Linda
    last_name: Muñoz
    gender: F
  - 25:
    first_name: Adrian
    last_name: Zavala
    gender: M
job:
  - Véterinario
  - Piloto
  - Policía
  - Bombero
  - Deportista
  - Ingeniero
  - Abogado
  - Médico
  - Cardiólogo
  - Community manager
  - Científico
  - Maestro
  - Actor
  - Dentista
  - Historiador
  - Presentador de televisión
  - Maestro de inglés
  - Cantante
  - Enfermero
  - Juez
  - Creador de videojuegos
  - Escritor
  - Explorador
  - Fotografo
  - Pediatra
presentation:
  - Me gusta mucha ir a la escuela y sobre todos las clases de educación física.
  - Tengo 8 años y medio. Soy muy tranquilo y me gusta cuando plantamos cosas en el huerto.
  - ¡Hola! Tengo 8 años y me gusta mucho el deporte.
  - Me gustan las historias de terror y también ir a la biblioteca para escuchar a los cuenta cuentos.
  - Tengo 7 años. Me gusta cantar todo el tiempo y participo en el coro de la escuela.
  - Me gusta la música y bailar también, me pone de buen humor. Tengo 8 años.
  - Hello, soy feliz y me gustan los animales. Sobre todo los perros y los caballos.
  - Hola a todos. Tengo 7 años y me gusta ir a la escuela, mi materia favorita es el inglés.
  - Me gustan los coches, los camiones de bomberos y los aviones también.
  - Saludos terrícolas. Tengo 6 años y me gustan los dulces. Mi mamá dice que no debo comer muchos, si no voy a tener caries.
  - Buenos días. Yo tengo 8 años, me gusta salir a jugar, correr y hacer pasteles de chocolate con mi hermana.
  - Yo tengo casi 8 años. Prefiero las clases de geografía y matemáticas.
  - A mi me gustan las aventuras y siempre encuentro una en la escuela.
  - Me gusta ir con mi papá a recoger conchitas en la playa. También me gusta las clases de artes en la escuela.
  - Hola, yo tengo 7 años y me gusta viajar y los poemas.
  - Hello, a mi me gusta ir a la escuela porque me divierto mucho con mis amigos, sobre todo a la hora del recreo.
  - Yo tengo 8 años y tengo un gato muy bonito que se llama Bigotes. Me gustan mucho los animales.
  - Saludos a todos los alumnos y a la maestra. Tengo 8 años y me gustan muchas las películas de superhéroes.
  - Hola, tengo 7 años y sé hacer algunos trucos de magia. Mi abuelito me enseñó.
  - Hola. Me gustaría caminar sobre la luna un dia. ¡Es mi sueño!
  - Tengo 8 años y me gusta inventar historias con héroes y sus aventuras.
  - Saludos, a mi me gusta cocinar. Mi mamá me enseñó a hacer galletas de vainilla y pastel de chocolate. Es muy fácil.
  - Hello ! Este verano fui a Estados Unidos con mi familia y aprendí algunas palabras en inglés.
  - Hola a todos, me gusta muy el deporte. Estoy en el équipo de natación y gané una medalle de oro en las competencias pasadas.
like:
  - Las canciones de amor
  - Las hamburguesas
  - Ir a la alberca
  - Las historias de terror
  - Ir a pescar con mi papá
  - Spaguetti a la boloñesa
  - Jugar con mi gato
  - El helado de vainilla
  - Todos los animales
  - Las pizzas
  - Plantar árboles
  - Mi perro
  - Cuando hace sol
  - El chocolate
  - Dibujar
  - Cantar
  - Comer palomitas de maíz
  - Las matemáticas
  - Los poemas
  - La mostaza
  - Los caballos
  - Los perros
  - Los gatitos
  - Las adivinanzas
  - Beneylu School
  - Ver películas
  - Comer chocolate
  - Los video juegos
  - Pintar
  - Los coches
  - El deporte
  - Leer historietas
  - Star Wars
  - Las caricaturas
  - Andar en bicicleta
  - Esquiar
  - Mi familia
  - Las vacaciones
  - Los dulces
  - Los cumpleaños
  - Ir a fiestas
  - Andar a caballo
  - El flamenco
  - Jugar a la loteria
  - Ir a la feria
  - La magia
  - Las malteadas
  - La playa
  - Los chistes
  - Patinar
dislike:
  - Las malas calificaciones
  - Hacer la tarea
  - La lluvia
  - El brocoli
  - Ir al dentista
  - cuando se terminan las vacaciones
  - Las injusticias
  - Los chicharos
  - Las matemáticas
  - Esperar todo el año para que sea Navidad
  - Cuando no entiendo un chiste
  - La gente mala
  - Cuando me castigan
  - El verde
  - La mostaza
  - Los tomates
  - Las tortugas
  - La gramática
  - La sopa de verduras
  - El rojo
  - La música clásica
  - Las mentiras
  - La maldad
  - Estar de mal humor
  - Cuando ensucio mi ropa
  - Las guerras
  - Aburrirme
  - Las tareas durante las vacaciones
  - La gramática
  - La ortografía
  - Los lunes
  - La comida de la cafetería
  - El frío
  - La noche
  - Los fantasmas
  - El pescado
  - La carne
  - Viajar en tren
  - El inglés
  - Enfermarme
  - Llegar tarde a la escuela
  - Caerme
  - La comida que pica
  - Los gatos agresivos
  - Ir al supermercado con mi mamá
  - Cargar mi mochila
  - Los exámenes
  - Ir al doctor
  - El betabel
  - Escribir mucho

status:
  - 1:
    text: Ganamos el partido de futbol ayer. ¡Vamos por el segundo partido!
    comments:
    - Bravo, ganaremos también mañana
    - Tenían un buen portero
  - 2:
    text: ¿Qué es una cosa verde que sube y que baja? Un chicharo en un ascensor
    comments:
    - Jajaja
    - Muy buen chiste
  - 3:
    text: ¡Ya quiero que lleguen las vacaciones!
    comments:
    - ¡Ya casi!
    - Yo también, pero solo al principio, porque después me aburro un poco.
    image: fleur.jpg
  - 4:
    text: Estoy muy contento porque hoy es mi cumpleaños. ¡Vamos a comer pastel! :-)
    comments:
    - ¡Feliz cumpleaños!
    - Yo quiero pastel
    - Te he traido un regalo
  - 5:
    text: Mañana vamos a la pischina y esta vez voy a saltar desde el trampolín.
    comments:
    - ¡Que valiente eres!
    - Bravo, vendré a echarte porras.
    - Super.
  - 6:
    text: Vi la película de Bob Esponja, ¡es super divertido!
    comments:
    - yo la voy a ver con mi hermano el próximo fin de semana.
    - A mi no me gusta Bob Esponja
    - Yo la vi y no me gustó.
  - 7:
    text: Tengo alergia a causa del polen y no dejo de estornudar.
    comments:
    - Mi hermana tiene la misma cosa.
    - ¡Salud!
  - 8:
    text: Ya terminé la tarea para mañana. El ejercicio de matemáticas estuvo algo dificil pero creo que me salió bien.
    comments:
    - Yo todavía no lo he empezado...
    - Yo tampoco.
  - 9:
    text: Fui a patinar con mi hermana ayer, y había muchos niños de nuestra edad que estaban jugando y andando en bicicleta.
    comments:
    - Invitame la próxima vez.
    - Yo también fui, pero casi en la noche.
  - 10:
    text: El próximo fin de semana mis papás van a llevarme a visitar el Castillo de Chapultepec
    comments:
    - ¡Super!
    - Toma muchas fotos.
  - 11:
    text: ¿A donde van a ir estas vacaciones?
    comments:
    - Yo voy a ir a Francia a visitar a mi tia.
    - Nosotros vamos a ir a la playa y nos vamos a quedar a acampar ahí.
    - Yo todavía no sé.
  - 12:
    text: Los juegos para la kermesse están listos.
    comments:
    - Nosotros nos encargamos de la decoración.
    - Yo invité a toda mi familia.
  - 13:
    text: Acabo de terminar el libro que pedí prestado en la biblioteca. Ya quiero leer la segunda parte.
    comments:
    - Yo estoy leyendo La Cenicienta.
    - Yo casi termino la segunda parte de Harry Potter.
  - 14:
    text: Ayer vi un reportaje sobre los gladiadores en la tele. Eran super fuertes!
    comments:
    - Yo también vi el reportaje.
    - ¿En qué canal lo pasaron?.
  - 15:
    text: Alguien cuenteme un chiste
    comments:
    - Dos caracoles se pasean en la playa. En el camino, se cruzan con un gusano. En ese momento se dan la vuelta "estamos en la playa de nudistas"
    - Jajajaja
  - 16:
    text: Mañana, durante el recreo, organizamos un juego de escondidas con todo el grupo.
    comments:
    - Me gusta la idea.
    - Yo quiero jugar
  - 17:
    text: ¿Qué cosa es una amigdala?
    comments:
    - No tengo idea.
    - ¿No es una cosa que tenemos en la garganta?
  - 18:
    text: Me gusta escuchar música. Sobre todo las canciones de Violeta.
    comments:
    - A mi también me gusta, ella es muy bonita.
    - ¿Qué les parece si hacemos una coreografía?
  - 19:
    text: Mi abuelita me enseñó a hacer paella, es una plato español con almejas, pollo, camarones y arroz amarillo.
    comments:
    - ¿Cómo le hace para que el arroz se pinte de amarillo?
    - A mi no me gustan los camarones.
    - A mi no me gusta eso.
  - 20:
    text: ¿Alguien escucha el programa de Manu en la radio?
    comments:
    - Si, yo lo escucho cuando voy en el coche para ir a la escuela.
    - Yo lo escucho en mi casa mientras me preparo para salir.
  - 21:
    text: ¿Quién piensan que ganará el partido mañana?.
    comments:
    - Yo digo que va a ser empate 1-1.
    - México 5 - Colombia 2
  - 22:
    text: Estoy de buen humor, mañana se terminan las clases
    comments:
    - El último día de clases de mi hermano fué ayer
    - Yeeeeees
  - 23:
    text: Tengo un pez que se llama Boris. Lo gané en la feria y mi mamá le comprú un pecera.
    comments:
    - Me gusta el nombre
    - Yo tengo un gato que se llama Calcetín.
  - 24:
    text: Me caí ayer y la enfermera me puso una bandita color naranja.
    comments:
    - ¡Ayyyyyy!
    - Te ha de haber dolido mucho
  - 25:
    text: Mañana en la cafetería habrá hamburguesas. Es mi plato favorito.
    comments:
    - A mi también me gustan
    - ¡Si, con papas a la francesa!
