name:
  - Escuela Independencia
  - Escuela Jean Piaget
  - Colegio de los Ni침os
  - Colegio de la Asunci칩n
uai:
  - 123456X
  - 654321X
  - 789456X
  - 456321X
address:
  - Calle de la Liberaci칩n, 1
  - Avenida de la Primavera, 3 
  - Calle de la Paz, 18
  - Camino de la cascada, 14
  - Calle de Marsella, 55
zipcode:
  - 93230
  - 55000
  - 90217
  - 78400
  - 55000
city:
  - Bogot치
  - Veracruz
  - Madrid
  - Buenos Aires
  - Cali
  - Santiago
  - Guadalajara
home_message:
  - Bienvenidos al espacio de nuestra escuela
  - Les damos la bienvenida a la plataforma digital de nuestra escuela
  - Descubran los mensajes que hemos escrito en el blog