datas:
  - 1:
    first_name: Antonio
    last_name: Hernández
    gender: M
  - 2:
    first_name: Silvia
    last_name: Torres
    gender: F
job:
  - Maestro de primaria
  - Maestra de inglés
presentation:
  - Bienvenidos a mi perfil en Beneylu School
  - Queridos alumnos, pueden comunicarse conmigo utilizando la mensajería
like:
  - Los alumnos inteligentes
  - La historia
  - La geografía
  - Las matemáticas
  - Los viajes
dislike:
  - Las malas calificaciones
  - El futbol
  - Cuando hace mucho calor
  - La comida picante
  - Cocinar
  - Lavar los platos
status:
  - 1:
    text: ¿Que tal si escriben un comentario sobre este mensaje?
    comments:
    - ¡Aquí está uno!
    - Pude dejar un comentario
    - ¡Muy fácil!
  - 2:
    text: Descubrí un lago escondido cerca de mi casa, ¡el atardecer en este lugar ha sido magnífico!
    comments:
    - ¡Que bonita fotografía!
    - A mi también me gusta la naturaleza