BNS\App\MiniSiteBundle\Model\om\BaseMiniSitePage:
  exclusion_policy: All
  properties:
      id:
        expose: true
      title:
        expose: true
      is_home:
        expose: true
      slug:
        expose: true
  virtual_properties:
    getType:
      expose: true
