<?php

namespace BNS\App\MediaLibraryBundle\Form\Type;

use BNS\App\MediaLibraryBundle\Form\Transformer\MediaToIdTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @author Jérémie Augustin <jeremie.augustin@pixel-cookers.com>
 */
class MediaIdType extends AbstractType
{
    /**
     * @inheritDoc
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new MediaToIdTransformer());
    }

    /**
     * @inheritDoc
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getParent()
    {
        return 'hidden';
    }


    /**
     * @inheritDoc
     */
    public function getName()
    {
        return 'media_id_type';
    }

}
