BNS\App\MediaLibraryBundle\Model\MediaFolderUser:
  exclusion_policy: All
  virtual_properties:
      getType:
        expose: true
      getChildrenWithPartial:
        expose: true
        max_depth: 2
        serialized_name: children
      getMarker:
        expose: true
      getIsWorkshopFolder:
        expose: true
        serialized_name: workshop_folder
      getUsageRatio:
        expose: true
      getUniqueKey:
        expose: true
        serialized_name: unique_key
      isReadable:
        expose: true
        serialized_name: readable
      isManageable:
        expose: true
        serialized_name: manageable
      isWritable:
        expose: true
        serialized_name: writable
      isFavorite:
        expose: true
        serialized_name: is_favorite
      isSystem:
        expose: true
        serialized_name: is_system
      getParentKey:
        expose: true
        serialized_name: parent_key
        groups: [media_folder_detail]
      getNiceUsage:
        expose: true
        serialized_name: usage
      getIsEmpty:
        expose: true
        serialized_name: is_empty
        groups: [media_folder_detail]
      getIsChildrenPartial:
        expose: true
        serialized_name: is_children_partial
