BNS\App\MediaLibraryBundle\Model\om\BaseMediaFolderGroup:
  exclusion_policy: All
  properties:
    id:
      expose: true
    status_deletion:
      expose: true
      groups: [media_folder_extra]
    is_private:
      expose: true
    is_locker:
      expose: true
    slug:
      expose: true
    created_at:
      expose: true
      groups: [media_folder_extra]
    updated_at:
      expose: true
      groups: [media_folder_extra]
