parameters:
#    bns_app_notification.example.class: BNS\App\NotificationBundle\Example

services:
#    bns_app_notification.example:
#        class: %bns_app_notification.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
