BNS\App\WorkshopBundle\Model\WorkshopWidgetGroup:
  exclusion_policy: All

  properties:
    percent:
      expose: true
      groups: [competition_statistics]
    score:
      expose: true
      groups: [competition_statistics]

  virtual_properties:
    getWorkshopWidgets:
      expose: true
      groups: [competition_statistics]
    getVersionCreatedBy:
      expose: true
      serialized_name: user_id
      groups: [competition_statistics]

  relations:
    - rel: self
      href:
        route: workshop_widget_group_api_get
        parameters:
            id: expr(object.getId())
            version: "1.0"
        absolute: true
    - rel: widgets
      embedded:
        content: expr(object.getWorkshopWidgets())
      exclusion:
        groups: [detail]
