parameters:
#    bns_app_fixture.example.class: BNS\App\FixtureBundle\Example

services:
#    bns_app_fixture.example:
#        class: %bns_app_fixture.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
