event:
  - 1:
    title: Stages de remise à niveau
    content: >
      <p>Les stages de remise à niveau ont lieu pendant les vacances scolaires. Les inscriptions se font auprès des établissements scolaires de vos enfants</p>
    start: 12
    end: 16
  - 2:
    title: Rencontre d’écrivains
    content: >
      5 écrivains viennent à la rencontre des élèves de l’école Jacques Prévert et du collège Evariste Galois pendant toute la semaine.
    start: 10
    end: 12
  - 3:
    title: Initiation aux premiers secours
    content: >
      <p>Après l’école Alphonse Daudet, c’est au tour de l’école élémentaire Victor Hugo de participer à des ateliers de premiers secours. Les 2 classes de CM2 assisteront à des ateliers menés par les Pompiers volontaires.</p>
    start: 9
    end: 11
    images:
      - sortie-caserne-pompiers.png
  - 4:
    title: Visite guidée du musée d’histoire naturelle
    content: >
      Dans le cadre de la liaison CM2-6ème, les élèves de l’école Gambetta et du collège Henri Matisse organisent une visite du Musée d’histoire naturelle.
    start: 10
    end: 11
  - 5:
    title: Rallye de calcul mental pour les écoles primaires
    content: >
     Les élèves de CM1 et CM2 participeront à un rallye de calcul mental. Les écoles gagnantes seront récompensées à la fin du mois.
    start: 13
    end: 15
  - 6:
    title: Diffusion de la première émission de radio de l’école Jean de La Fontaine
    content: >
      <p>Les élèves de CM1 et de CM2 ont créé, à l’aide de leurs enseignants, la première web radio de l’école. Leur première émission sera en ligne ce jour.</p>
    start: 15
    end: 16
  - 7:
    title: Sécurité routière
    content: >
      <p>Dans le cadre de la prévention sur la sécurité routière, les élèves de primaire et de collège seront initiés au code de la route.<br/>Du CP à la 5ème, les élèves seront formés sur la sécurité routière en vélo. </p>
    start: 9
    end: 11
    images:
      - initiation-au-velo-pour-les-enfants-de-3-10-ans.jpg
  - 8:
    title: Rencontre école-entreprise
    content: >
      <p>Les élèves rencontreront des professionnels pour découvrir le monde du travail. Les ateliers seront organisés sur 2 jours pour les élèves du CE2 à la 3ème.</p>
    start: 15
    end: 16
  - 9:
    title: Nuit de la lecture
    content: >
      Au collège Maupassant, les volontaires pourront passer la soirée au CDI pour la première nuit de la lecture. Des ateliers de présentation de livres et de lectures à voix haute seront organisés par les élèves et leurs professeurs, ainsi qu’une rencontre avec un écrivain.
    start: 10
    end: 12
  - 10:
    title: Rencontre avec des étudiants étrangers
    content: >
      Des étudiants étrangers viennent présenter leur pays et leur culture aux élèves de primaire.
    start: 16
    end: 18
  - 11:
    title: Grande chorale
    content: >
      Toutes les écoles élémentaires de l’académie sont invitées pour participer à la grande chorale au Centre Dramatique National.
    start: 16
    end: 18
  - 12:
    title: Initiation au sport
    content: >
      Les professeurs de l’école Henri Barbusse profitent de la Semaine Olympique et Paralympique pour relancer l’activité sportive à l’école.
    start: 16
    end: 18
    images:
      - echauffement.jpg
