event:
  - 1:
    title: Formation au numérique - Inscriptions
    content: >
      <p>Les inscriptions pour les formations au numérique se font auprès des chefs d’établissement. D’autres sessions sont prévues au cours de l’année scolaire.</p>
    start: 12
    end: 16
    images:
      - ecole-numerique-education-nationale.png
  - 2:
    title: Formation pour l’éducation à l’alimentation
    content: >
      <p>Des formations sont prévues pour les enseignants concernant l’éducation à l’alimentation. Les professeurs et assistants d’éducation intéressés peuvent prendre contact avec Mme Ginot pour s’inscrire.Des outils et ressources seront mis à disposition des participants à la fin de la formation.</p>
    start: 10
    end: 12
    images:
      - education-alimentation-eduscol.jpg
  - 3:
    title: Formation Apprendre à porter secours
    content: >
      <p> La circonscription met en place des formations pour aider les enseignants et assistants d’éducation dans l’éducation aux premiers secours. Les personnes intéressées peuvent s’inscrire auprès de leur chef d’établissement. </p>
    start: 9
    end: 11
  - 4:
    title: Semaine de la presse et des médias dans l’école
    content: >
      <p>Pour préparer la semaine de la presse et des médias dans l’école, le CLEMI (Centre de liaison de l'enseignement et des médias d'information) organise des formations sur l'éducation aux médias.</p>
    start: 10
    end: 11
    images:
      - spme.jpg
  - 5:
    title: Ateliers de sensibilisation au développement durable
    content: >
      Les écoles de la circonscription sont invitées à participer aux ateliers sur le développement durable proposés par des bénévoles.
    start: 13
    end: 15
    images:
      - education-developpement-durable.png
  - 6:
    title: Ateliers dans le potager de l’école Jacques Prévert
    content: >
      <p>Les élèves et leurs professeurs ont lancé un projet de potagers dans l’école. Ils ont planté des tomates, des salades, des carottes et des fraises.</p> <p>Ils ont été initiés au cycle de vie et de production des végétaux. Ils ont décidé d’organiser des ateliers de sensibilisation pour les autres écoles de la circonscription. Contactez la chef d’établissement Mme Henry pour participer.</p>
    start: 15
    end: 16
    images:
      - potager.jpg
  - 7:
    title: Formation Sécurité sur Internet
    content: >
      <p>La formation Sécurité sur Internet est destinée aux enseignants et aux assistants d’éducation pour le numérique. <br/>Les inscriptions se font auprès des chefs d’établissement.</p>
    start: 9
    end: 11
  - 8:
    title: Éducation à l’alimentation
    content: >
      <p>3 chefs cuisiniers viendront réaliser un atelier d’éducation à l’alimentation à l’école Victor Hugo.</p>
    start: 15
    end: 16
  - 9:
    title: Rencontre sportive entre les écoles de la circonscription
    content: >
     <p>La rencontre aura lieu au gymnase Maurice Baquet. Chaque classe participante est divisée en plusieurs groupes selon les disciplines : <br/><ul><li>basket</li><li>football</li><li>roller</li><li>thèque /li><li>lutte</li></ul>Un trophée sera donné aux équipes gagnantes pour chaque sport.</p>
    start: 10
    end: 12
    images:
      - victoire-equible-bleue.jpg
  - 10:
    title: Portes ouvertes du collège
    content: >
      Le collège Maupassant ouvre ses portes aux élèves de CM2 de la circonscription. Les 6ème organisent une visite guidée. Les CM2 pourront assister à une heure de cours et prendront leur repas à la cantine du collège.
    start: 16
    end: 18
  - 11:
    title: Liaison inter-degrés
    content: >
      Les élèves de GS de la maternelle Casanova viendront visiter l’école primaire Jules Vernes. Les CP visiteront la classe de GS l’après-midi.
    start: 16
    end: 18
  - 12:
    title: Natation à l’école
    content: >
      Les maîtres nageurs de la piscine organisent des ateliers pour apprendre aux élèves à apprivoiser l’eau. Les inscriptions se font auprès au secrétariat de la piscine.
    start: 16
    end: 18
    images:
      - piscine-apprivoiser-eau.jpg
  - 13:
    title: Cinéma
    content: >
      Le cinéma ouvre ses portes pour visionner des films d’animation éducatifs. Renseignez-vous auprès du secrétariat pour les programmes et les inscriptions.
    start: 16
    end: 18
  - 14:
    title: Séance de méditation au dojo
    content: >
      3 professeurs de yoga interviennent au dojo pour une séance de méditation. Inscrivez les classes auprès de votre chef d’établissement.
    start: 16
    end: 18
