event:
  - 1:
    title: FERMETURE EXCEPTIONNELLE À 12H !
    content: >
      <p>Bonjour à tous, le centre de loisirs sera fermé vendredi 16 février à partir de 12h en raison de la coupure de courant du quartier. Merci de votre compréhension !</p>
    start: 12
    end: 16
  - 2:
    title: Sortie à la ferme
    content: >
      Les enfants qui n'ont pas pu aller à la ferme en fin d'année ont droit à une séance de rattrapage :)
    start: 10
    end: 12
    images:
      - visite-de-la-ferme-gally.jpg
  - 3:
    title: Initiation au vélo
    content: >
      <p> Les enfants qui le souhaitent apprendront à faire du vélo et seront initiés au code des piétons et au code de la route.</p>
    start: 9
    end: 11
    images:
      - les-enfants-se-deplacent-a-velo-sur-le-circuit-permettant_2923486.jpg
  - 4:
    title: Initiation à la danse
    content: >
      Deux intervenantes proposent d'initier les enfants qui le souhaitent à la danse sous formes d'ateliers tout au long de la journée. Inscriptions auprès des animateurs.
    start: 10
    end: 11
  - 5:
    title: Initiation à la natation
    content: >
      Les enfants peuvent être initiés à la natation. Tous les matins, nous les emmenons à la piscine où les maîtres nageurs leur apprennent à nager. Si vos enfants veulent participer, inscrivez-les auprès des animateurs du centre de loisirs.
    start: 13
    end: 15
    images:
      - swim-619074_1920.jpg
  - 6:
    title: Semaine de la presse et des medias
    content: >
      <p>Nous organiserons une semaine spéciale pour la Semaine de la presse et des médias. Au programme, reportages, rédaction d'articles, émission de radio et journal de la semaine !</p>
    start: 15
    end: 16
    images:
      - semaine-presse-et-médias.jpg
  - 7:
    title: Atelier Bracelets eau et feu
    content: >
      On fabrique nos bracelets pour l'équipe de l'eau et l'équipe du feu.
    start: 9
    end: 11
    images:
      - perles.png
  - 8:
    title: Atelier manga
    content: >
      <p>On plonge dans l'univers... des mangas ! On lit et on dessine avec :<br/><br/>Chi, une vie de chat (dès 6 ans)<br/>Kamisama (dès 6 ans)<br/>Gon(dès 6 ans)</p>
    start: 15
    end: 16
    images:
      - Manga.png
  - 9:
    title: Piscine
    content: >
      Sortie piscine pour les 6-8 ans. Pour participer, inscrivez les enfants auprès des animateurs du centre.
    start: 10
    end: 12
    images:
      - swim-619074_1920.jpg
  - 10:
    title: Atelier Pixel Art
    content: >
      Le pixel art est la grande mode du moment. Cela plaît énormément aux enfants et c’est idéal pour le repérage dans l’espace.
    start: 16
    end: 18
    images:
      - Pixel-Art.jpg
  - 11:
    title: Initiation vélo
    content: >
      Initiation vélo au centre (Apporter son vélo et son casque en bon état)
    start: 16
    end: 18
    images:
      - les-enfants-se-deplacent-a-velo-sur-le-circuit-permettant_2923486.jpg
  - 12:
    title: Jeux de société
    content: >
      Au programme : Monopoly, Cluedo, Mission escape et la crique des pirates.
    start: 16
    end: 18
    images:
      - Jeux-société.png
  - 13:
    title: Atelier yoga
    content: >
      Nous apprenons les postures faciles du yoga en se relaxant et en jouant. Prévoir un jogging et un oreiller avec le nom de l'enfant.
    start: 16
    end: 18
    images:
      - Yoga.png
  - 14:
    title: Lecture de contes
    content: >
      On lit des contes au centre ! On découvre les contes à l'origine de Blanche-Neige, La petite sirène et Cendrillon.
    start: 16
    end: 18
    images:
      - bibliothèque.png
  - 15:
    title: Tartes aux pommes
    content: >
      Pour terminer la semaine en beauté, nous préparons des minis tartes aux pommes avec les enfants. Miam !
    start: 16
    end: 18
    images:
      - Tartes-aux-pommes.png
