event:
  - 1:
    title: Élections du Conseil municipal des jeunes
    content: >
      <p>Le Conseil Municipal des Jeunes (CMJ) est un lieu d'expression et d'échange qui permet aux jeunes d'être acteurs de leur ville, de découvrir la vie de la commune et de réaliser des projets, tout en favorisant leur apprentissage de la citoyenneté.
      Les jeunes conseillers sont des élèves en classe de 6e, 5e, 4e et CM2. Le mandat d'un jeune conseiller est fixé à deux ans.
      <strong>Objectifs</strong>
      Les objectifs du CMJ sont de :<ul>
      <li>prendre en compte la parole des jeunes ;</li>
      <li>leur permettre de participer à la vie sociale et locale ;</li>
      <li>les initier au civisme et à la citoyenneté ;</li>
      <li>renforcer la démocratie locale à travers le dialogue ;</li>
      <li>permettre aux jeunes de prendre conscience de leurs droits et leurs devoirs de citoyens ;</li>
      <li>obtenir les points de vue des jeunes sur les dossiers de la collectivité, dans différents domaines.</li> </ul>
      <strong>Le rôle du jeune conseiller </strong> <br/>
      Le statut de conseiller permet à un jeune de :<ul>
      <li>représenter les jeunes de la collectivité.</li>
      <li>dialoguer avec les élus et apporter un regard nouveau sur les projets de la municipalité qui les concernent</li>
      <li>proposer des actions en direction des jeunes et de la collectivité dans son ensemble.</li></ul>
      Au cours de leur mandat, les jeunes conseillers participeront à au moins une cérémonie patriotique en solidarité avec les générations précédentes ou à une manifestation municipale aux côtés de leurs aînés du Conseil Municipal. </p>
    start: 14
    end: 16
  - 2:
    title: Initiation à la natation
    content: >
     Les maîtres nageurs de la piscine municipale organisent une initiation à la natation le 21 février prochain.
    start: 10
    end: 12
  - 3:
    title: Ateliers sportifs
    content: >
     <p> 5 entraîneurs organisent des ateliers sportifs au gymnase Maurice Baquet.
     Au programme :<br/> aïkido, escrime, sprint, gymnastique rythmique et escalade.
     Inscriptions sur le site de la mairie.</p>
    start: 9
    end: 11
  - 4:
    title: Semaine du goût à l’école
    content: >
     Bien manger, bien bouger !
    start: 10
    end: 11
  - 5:
    title: Conseil municipal
    content: >
      Les séances du conseil municipal sont ouvertes à tous !
    start: 13
    end: 15
  - 6:
    title: Atelier sérigraphie à Guillevic
    content: >
      <p><strong>Venez avec votre enfant partager un moment de plaisir et de créativité.</strong><br/>
      Nous réaliserons ensemble une affiche que vous pourrez emporter chez vous et qui sera l'emblème de l'espace parent.<br/>
      Nous découvrirons ensemble, la sérigraphie.<br/>
      <strong>Parents, grands-parents ,enfants, instituteurs … Soyez les bienvenus!</strong><br/>
      L'inscription se fait auprès des animateurs du centre de loisirs de Guillevic.</p>
    start: 15
    end: 16
  - 7:
    title: Fête des écoles
    content: >
      Chaque école maternelle et élémentaire ouvre ses portes aux parents pour la fête des écoles ! Au programme : visite des classes, ateliers d'élèves, dégustation sur les stands, rencontre avec les enseignants, parcours piétons, jeux concours…
    start: 9
    end: 11
  - 8:
    title: Festival des livres
    content: >
      Le Festival des livres a lieu tout le weekend. Rencontrez les auteurs, découvrez les collections de la bibliothèques, trouvez votre prochain livre en parcourant la ville !
    start: 15
    end: 16
  - 9:
    title: Journée bien-être
    content: > Venez en famille !
    start: 10
    end: 12
  - 10:
    title: Fête du jeu et de la parentalité
    content: > Venez nombreux !
    start: 16
    end: 18