event:
  - 1:
    title: Bibliothèque
    content: Ne pas oublier de ramener les livres de bibliothèque ;-)
    start: 14
    end: 16
  - 2:
    title: Sport
    content: Cette semaine on fait de la course à pied.
    start: 10
    end: 12
  - 3:
    title: Piscine
    content: Prenez bien vos bonnets de bain.
    start: 9
    end: 11
  - 4:
    title: Musique
    content: Chorale.
    start: 10
    end: 11
  - 5:
    title: Jardinage
    content: On plante les carottes cette semaine.
    start: 13
    end: 15
  - 6:
    title: Goûter d'anniversaire
    content: On mangera du gâteau au chocolat !
    start: 15
    end: 16
  - 7:
    title: Echange avec nos correspondants anglais
    content: Cette semaine on se présente.
    start: 9
    end: 11
  - 8:
    title: Visite au zoo
    content: Prenez vos appareils photo.
    start: 15
    end: 16
  - 9:
    title: Préparation de la kermesse
    content: Atelier décorations en papier.
    start: 10
    end: 12
  - 10:
    title: Foot inter-classes
    content: Compétition mixte.
    start: 16
    end: 18
  - 11:
    title: Initiation à la danse africaine
    content: Prenez vos affaires de sport.
    start: 9
    end: 12
  - 12:
    title: Spectacle de marionnettes
    content: Avec la compagnie Marion Nette
    start: 14
    end: 16
  - 13:
    title: Sport
    content: Cette semaine on fait du karaté.
    start: 10
    end: 12
  - 14:
    title: Atelier code de la route
    content: Il aura lieu dans la cour, en vélo.
    start: 14
    end: 15
  - 15:
    title: Atelier journalisme
    content: Volontaires pour le journal de l'école.
    start: 11
    end: 12
  - 16:
    title: Atelier bruitages du cinéma
    content: Sur un film de Jean-Pierre Jeunet.
    start: 17
    end: 18
  - 17:
    title: Concours d'orthographe
    content: Une dictée de 100 mots.
    start: 8
    end: 10
  - 18:
    title: Contes
    content: Avec les bibliothécaires.
    start: 14
    end: 16
  - 19:
    title: Jardinage
    content: Cette semaine on désherbe.
    start: 13
    end: 15
  - 20:
    title: Sortie au bois
    content: On fera un herbier.
    start: 10
    end: 12
  - 21:
    title: Cross
    content: Que le meilleur gagne !
    start: 14
    end: 16
  - 22:
    title: Cinéma
    content: On regarde Hugo Cabret
    start: 13
    end: 16
  - 23:
    title: Piscine
    content: On apprend à mettre la tête sos l'eau.
    start: 9
    end: 11
  - 24:
    title: Art du cirque
    content: On fait du diabolo
    start: 8
    end: 10
  - 25:
    title: Cuisine
    content: On fait du clafoutis aux cerises
    start: 10
    end: 12
  - 26:
    title: Lecture numérique
    content: Sur les tablettes.
    start: 9
    end: 10
  - 27:
    title: Musique
    content: On fait des percussions.
    start: 10
    end: 11
  - 28:
    title: Informatique
    content: Rédaction sur le blog Beneylu School.
    start: 14
    end: 16
  - 29:
    title: Rallye-lecture
    content: On répond aux questions.
    start: 9
    end: 10
  - 30:
    title: Arts plastiques
    content: On fait de la peinture.
    start: 13
    end: 15