event:
  - 1:
    title: Inauguration du campus des métiers
    content: >
      <p>Le recteur de l’académie a inauguré le Campus des métiers. C’est un projet qui est porté depuis le début de l’année par le lycée professionnel Jules Vernes.</p>
    start: 12
    end: 16
  - 2:
    title: Semaine de la presse et des médias dans l’école
    content: >
      <p> Dans le cadre de la Semaine de la presse et des médias dans l'école, le recteur a remis leur diplôme aux lauréats du Prix Jeune reporter d'images. </p>
    start: 10
    end: 12
    images:
      - travail-en-groupe-spme.jpg
  - 3:
    title: Remise du Grand Prix Hippocrène au collège Colette
    content: >
      <p> Le collège Colette a remporté le Grand Prix du concours Hippocrène de l'éducation à l'Europe !</p>
    start: 9
    end: 11
  - 4:
    title: Semaine de l’Industrie
    content: >
      Le ministère l'Éducation nationale participe à la Semaine de l'industrie pour sensibiliser les élèves au secteur industriel et à ses métiers.
    start: 10
    end: 11
    images:
      - semaine-industrie.png
  - 5:
    title: Éducation musicale : les écoles participent au Festival École en choeur
    content: >
      Le "Festival École en choeur" met à l'honneur les chorales scolaires pour favoriser et développer l'éducation musicale et le chant choral au sein de l'école.
    start: 13
    end: 15
    images:
      - 2018-ecolenchoeur.jpg
  - 6:
    title: Inscriptions sur ParcourSup
    content: >
      <p>Pensez à vous inscrire sur ParcourSup !</p>
    start: 15
    end: 16
  - 7:
    title: Demande de bourses de lycée : tout en ligne
    content: >
      <p>Pour l’année prochaine, le service de demande de bourses pour les lycées est entièrement en ligne. Rendez-vous sur le portail Scolarité-Services de l’académie pour en faire la demande. </p>
    start: 9
    end: 11
  - 8:
    title: Prix du concours “Non au harcèlement”
    content: >
      <p>Le « Prix coup de cœur académique » a été remis au collège Georges Clémenceau pour son affiche. Bravo aux élèves ! <br/>
      Les résultats du concours national seront dévoilés à la fin de l’année.</p>
    start: 15
    end: 16
  - 9:
    title: Olympiades des métiers
    content: >
      <p>Les épreuves régionales des Olympiades des métiers ont lieu à partir de 9h. 256 candidats sont en lice, bonne chance à eux !</p>
    start: 10
    end: 12
    images:
      - olympiades-metiers_logo.jpg
      - olympiades-metiers-pole-industrie.jpg
  - 10:
    title: Semaine de l’Économie Sociale et Solidaire à l’école
    content: >
     <p>C’est la Semaine de l’Économie Sociale et Solidaire à l’École. L’objectif est de sensibiliser les élèves de la maternelle au lycée aux façons collectives d’entreprendre : associations, mutuelles, coopératives.</p>
    start: 16
    end: 18
    images:
      - semaine-economie-sociale-solidaire-ecole.png
  - 11:
    title: Rencontres d’écrivains
    content: >
      <p>10 écrivains jeunesse viennent à la rencontre des élèves du CE2 à la terminale pour parler lecture et écriture. Les écrivains échangeront avec les élèves sur leur oeuvre, leur métier et le processus de création. </p>
    start: 16
    end: 18
    images:
      - bibliotheque.png
