blog:
 - 1:
   title: Sortie en forêt
   content: >
     <p>Vendredi, pour terminer les vacances en beauté, nous sommes allés en forêt. Retour sur une journée bien chargée.
     Au programme de la matinée : construction de cabanes ! Chaque groupe et son animateur a construit une cabane dans la forêt. Voici Élisa, Manon et Tiago en plein travail : <br/>
     <p>Le midi, nous nous sommes arrêtés prêts d'une drôle de sculpture, pour le plus grand bonheur des enfants.</p>
     <p>Nous avons ensuite passé l'après-midi à l'accrobranche... Sensations garanties.</p>
     Entre l'escalade et la tyrolienne, tout le monde s'est bien amusé... et chacun est prêt pour la rentrée !
     </p>
   images:
     - ramassage-bois.jpg
     - sculpture.jpg
     - accrobranche.jpg
     - accrobranche2.jpg
     - tyrolienne.jpg
   category: Sport
 - 2:
   title: Initiation à la natation
   content: >
     <p style="text-align: justify;">Nous vous informons qu'une initiation à la natation aura lieu à la piscine <strong>pendant les vacances de février.</strong> <br/> Les inscriptions se font auprès des animateurs du centre. Merci !</p>
   images:
     - swim-619074_1920.jpg
   category: Sport
 - 3:
   title: Du sport au centre de loisirs
   content: >
     <p>Cette semaine, nous avons organisé un mercredi sportif ! <br/>
     Les enfants ont pu jouer au football, au basket, courir et faire de la gym. <br/>
     Nous avons commencé par apprendre à nous échauffer sur le sol du gymnase. <br/>
     Voici les résultats : <br/>
     Au basket, c'est l'équipe jaune qui a gagné.<br/>
     Au sprint, bravo à Jules pour sa super performance !<br/>
     L'équipe verte a gagné la compétition de gym.<br/>
     Et les bleus (et oranges) se sont illustrés en football, remportant le trophée :<br/>
     Bravo à toutes nos graines de champions !</p>
   images:
     - echauffement.jpg
     - victoire-equible-bleue.jpg
   category: Sport
 - 4:
   title: La ferme de Gally
   content: >
     <p>Cette semaine, nous avons emmené les enfants en sortie à la ferme. Nous avons rencontré plusieurs animaux. Les fermiers nous ont expliqué comment ils nourrissent les vaches, les chevaux, les chèvres et autres oiseaux qui vivent dans la ferme.
     <p>Nous avons pu entrer dans les enclos des animaux. Certains ont même pu leur donner à manger !</p></p>
   images:
     - perruches.jpg
     - chevre.jpg
   category: Sorties
