blog:
 - 1:
   title: Initiation au vélo
   content: >
     <p>Des intervenants sont venus dans les écoles élémentaires du département pour initier les élèves au vélo.<br/>Les élèves de CM1 et CM2 ont appris à maîtriser leur vélo et ont appris quelques règles en matière de sécurité routière.</p>
   images:
     - prevention-securite-routiere-velo.jpg
   category: prévention
 - 2:
   title: Éducation à l’alimentation
   content: >
     <p style="text-align: justify;">Les écoles élémentaires Jules vernes et George Sand ont organisé des ateliers en collaboration avec des chefs cuisiniers. Ils ont appris à préparer des plats variés et équilibrés.<br/>Ils ont aussi goûté des aliments, à commencer par l’eau plate et l’eau pétillante.</p>
   images:
     - eles-goutent-eau-semaine-du-gout.png
   category: prévention
 - 3:
   title: Une journée au collège
   content: >
     <p>Les CM2 de l’école élémentaire Jean Jaurès ont passé une journée avec les élèves de 6ème du collège Emile Zola.  <br/>Après une visite guidée réalisée par les élèves de 6ème, les CM2 ont assisté à des cours et ont découvert la cantine du collège. <br/>Les CM2 accueilleront les élèves du collège dans leur école le mois prochain.</p>
   category: liaison inter-écoles
 - 4:
   title: Écoles numériques
   content: >
     <p>Équipées d’ordinateurs, les élèves des écoles Jacques Prévert et Henri Barbusse apprennent à taper au clavier et à utiliser Internet.</p>
   images:
     - ecole-numerique.png
   category: numérique
 - 5:
   title: Apprendre à vivre en société
   content: >
     <p>Les élèves de 500 classes de primaire sont formés jusqu’à la fin de l’année scolaire aux droits et devoirs des citoyens. L’enjeu est d’apprendre à vivre en société et de se respecter, dans la vie comme sur Internet.</p>
   category: prévention
