blog:
 - 1:
   title: Semaine de la presse et des médias dans l’école
   content: >
     <p>Pour préparer la semaine de la presse et des médias dans l’école, le CLEMI (Centre de liaison de l'enseignement et des médias d'information) organise des formations sur l'éducation aux médias. <br/>Une banque de ressources et outils est disponible pour les enseignants. Profitez-en pour lancer votre blog de classe (blog Beneylu School) ou votre web radio (enregistreur audio de l’atelier). Des manuels d’utilisation vous aident à utiliser les applications Beneylu School.</p>
   images:
     - spme.jpg
   category: formations
 - 2:
   title: Finale - écoles Henri Barbusse et Jacques Prévert
   content: >
     <p style="text-align: justify;">Les CM1 de l’école Henri Barbusse ont remporté la finale de football inter-école face aux élèves de Jacques Prévert, bravo à eux !</p>
   category: événements
 - 3:
   title: Formation au numérique
   content: >
     <p>PLes enseignants des écoles primaires de la circonscription se sont formés au numérique cette semaine. Les échanges ont porté sur :<ul><li>la sécurité sur Internet<li/><li>les exemples d’usages d’Internet en classe<li/><li>l’équipement matériel pour naviguer sur le web à l’école.<li/><ul/><br/>Les enseignants des écoles maternelles pourront suivre la même formation.</p>
   category: formations
 - 4:
   title: Fête de la science
   content: >
     <p>Dans le cadre de la liaison inter-degrés, les élèves de CM2 et de 6ème ont collaboré pour organiser des expériences à l’occasion de la Fête de la science. <br/>Ils ont prouvé à leurs camarades l’existence de l’air en quelques gestes simples.</p>
   images:
     - fete-science-experience-air.jpg
   category: événements
 - 5:
   title: L’école Jacques Prévert se lance dans le potager
   content: >
     <p>Les élèves de l’école Jacques Prévert ont installé des potagers dans la cour de récréation. Ils ont planté des tomates, des salades et des carottes. Récoltes à suivre…</p>
   images:
    - potager.jpg
   category: projet
 - 6:
   title: Correspondance scolaire
   content: >
     <p>Les élèves de CM1 de l’école Jules Vernes partiront à Glasgow (Écosse) visiter leurs correspondants. Ils échangent depuis le début de l’année avec les élèves de Netherlee Primary School avec la messagerie et le blog Beneylu School. </p>
   images:
    - recherche-ville-des-correspondants.png
   category: projet
