blog:
 - 1:
   title: Activités péri et extrascolaires 2017-2018
   content: >
     <p>Le Guide des activités péri et extrascolaires 2017-2018 est disponible. Vous y retrouverez toutes les informations nécessaires pour que votre enfant puisse fréquenter les centres de loisirs cet été.</p>
   images:
     - guide-activites-peri-extra-scolaires.png
     - rennes-activites-peri-extra-scolaires.pdf
   category: Périscolaire
 - 2:
   title: L'heure du conte à la bibliothèque municipale
   content: >
     <p style="text-align: justify;">Pour les enfants de 4 à 8 ans, les bibliothécaires ont mis en place "L'heure du conte". Tous les samedis à 17h, un conte sera lu aux enfants ou une histoire sera racontée par un conteur professionnel !<br/>Inscriptions sur le site de la bibliothèque.</p>
   images:
     - lecture-bibliotheque.jpg
   category: Bibliothèque Théodore Monod
 - 3:
   title: Vacances scolaires
   content: >
     <p>Pour connaître le centre de loisirs municipal le plus proche de chez vous, rendez-vous sur le site de la mairie, dans la rubrique Informations pratiques / Centres de loisirs / Petites vacances scolaires.<br/>
        Les centres de loisirs sont ouverts pendant toute la période des vacances.<br/>Pensez à réserver (et à annuler) les jours de présence de votre enfant au plus tard 8 jours avant la fréquentation.<br/>La réservation est obligatoire. <br/>À compter du mois prochain, une tarification spécifique sera appliquée en cas de non réservation préalable ou de réservation non honorée <strong>sur les mercredis et les vacances scolaires. </strong></p>
   images:
     - centre-de-loisirs-guillevic.jpg
   category: Calendrier
 - 4:
   title: Initiation au théâtre
   content: >
     <p>3 metteurs en scène et comédiens proposent des ateliers théâtre aux élèves de primaire. Les ateliers d'initiation démarreront après les vacances.<br/>Pour inscrire les classes, envoyez un mail à : secretariat.theatre@gmail.com </p>
   images:
     - initiation-theatre.jpg
   category: Théâtre Jacques Brel
 - 5:
   title: Petites vacances – ouverture des centres
   content: >
     <p>Les petites vacances approchent, il est temps d’inscrire vos enfants ! <br/>Les enfants seront accueillis comme habituellement dans leur centre de loisirs du mercredi, après la classe.<br/>
        Les centres de loisirs des petites vacances ouvriront leurs portes pour toute la durée des vacances.<br/>À noter : les centres de loisirs sont fermés les jours fériés.<br/>Pensez à regarder régulièrement le blog et le panneau d’affichage de votre centre de loisirs pour connaître les jours de fermeture du centre.</p>
   category: Calendrier
