blog:
 - 1:
   title: Prévention du cyber-harcèlement
   content: >
     <p>Les élèves de 500 classes de primaire sont formés jusqu’à la fin de l’année scolaire aux droits et devoirs des citoyens sur internet. La formation est principalement axée sur la prévention du cyber-harcèlement.</p>
   images:
     - prevention-harcelement.jpg
   category: prévention
 - 2:
   title: Une journée au Moyen-âge
   content: >
     <p style="text-align: justify;">L’école élémentaire Jean Jaurès et le collège Emile Zola ont mis en place une journée thématique autour du Moyen-âge. <br/>Les élèves organisateurs et leurs professeurs ont proposé plusieurs ateliers pour illustrer la vie à l’époque médiévale : pratiques sportives (escrime et tir à l’arc), musique, création de blasons et quizz.</p>
   images:
     - journee-moyen-age.jpg
   category: journées thématiques
 - 3:
   title: Éducation à la sécurité routière
   content: >
     <p>Des agents de la Sécurité publique de la Police nationale sont intervenus dans les écoles élémentaires de l’académie pour initier les élèves à la sécurité routière.<br/>Les élèves de CM1 et CM2 ont appris à utiliser leurs vélos sur la route en toute sécurité grâce à plusieurs ateliers. Désormais, ils maîtrisent leur vélo et ont approfondi leur connaissance des règles de sécurité routière.</p>
   images:
     - les-enfants-se-deplacent-a-velo-sur-le-circuit-permettant_2923486.jpg
   category: Calendrier
 - 4:
   title: Semaine du goût
   content: >
     <p>À l’occasion de la semaine du goût, les écoles élémentaires Jules vernes et George Sand ont organisé des ateliers en collaboration avec des chefs cuisiniers. <br/>Ils ont appris à manier les saveurs et à préparer des plats variés et équilibrés. Ils ont aussi appris quelques gestes importants : bien fermer le robinet, se laver les mains avec du savon, rincer les légumes en récupérant l’eau pour arroser les plantes de l’école ou encore trier les déchets.</p>
   category: école-entreprise
 - 5:
   title: Les écoles passent au numérique
   content: >
     <p>L’enseignement numérique fait partie des programmes scolaires. Ainsi, les écoles élémentaires de l’académie s’équipent progressivement en matériel informatique : ordinateurs, tablettes et TBI (Tableaux Blancs Interactifs).<br/> Les enseignants et assistants d’éducation apprennent aux élèves à taper au clavier et à utiliser Internet.</p>
   images:
    - ecole-numerique.png
   category: numérique
 - 6:
   title: Rencontres avec les professionnels
   content: >
     <p>Les élèves des écoles élémentaires Jean Jaurès et Jules Ferry ont mis un pied dans le monde professionnel. Ils ont observé des artisans, des commerçants et les pompiers.</p>
   images:
    - la-visite-chez-les-pompiers.png
   category: école-entreprise
 - 7:
   title: Rencontres d’écrivains
   content: >
     <p>10 écrivains jeunesse sont venus à la rencontre des élèves du CE2 à la terminale pour parler lecture et écriture. <br/>Les élèves ont posé des questions sur les livres, le métier d’écrivain et sur la création d’une histoire</p>
   images:
    - questions-eleves.jpg
   category: école-entreprise
 - 8:
   title: Initiation à la programmation
   content: >
     <p>Les CM2 de l’école René Coty sont initiés à la programmation depuis le début de l’année. Ils ont commencé par apprendre à coder</p><p>Ils apprennent maintenant à programmer des petits robots et leur enseignante a invité des professionnels pour poursuivre le projet.</p>
   images:
    - seance-code.jpg
   category: numérique
 - 9:
   title: Prix du concours “Non au harcèlement”
   content: >
     <p>Le « Prix coup de cœur académique » a été remis au collège Georges Clémenceau pour son affiche. Bravo aux élèves !</p><p>Le jury a également sélectionné six établissements pour concourir au niveau national.<br/>Dans la catégorie « 8-11 ans » ont été sélectionnées l’affiche du collège Jean Moulin et la vidéo réalisée par les élèves de l’école Anne Franck.<br/>Dans la catégorie « 12-15 ans » ont été sélectionnées l’affiche du collège Georges Clémenceau et la vidéo du collège Gérard Philippe.<br/>Dans la catégorie « 15-18 ans » ont été sélectionnées l’affiche du lycée René Coty et la vidéo du lycée professionnel Romain Rolland.<br/>Les résultats nationaux seront diffusés à la fin de l’année.</p>
   images:
    - seance-code.jpg
   category: prévention
