name:
  - Circonscription d'Isserteaux
zipcode:
  - 35000
city:
  - Rennes
home_message:
  - Bienvenue dans l'espace de notre circonscription
  - Nous vous souhaitons bienvenue dans l'ENT de notre circonscription
