name:
  - CM2 rouge
  - CM1B
  - CP
  - CE2 bleu
  - CE1 vert
  - CM2
  - CE1 mauve
home_message:
  - Bienvenue dans l'espace de notre classe
  - Nous vous souhaitons bienvenue dans l'ENT de notre classe
  - Bonjour, Hello, Hallo, Buenos Dias, namaste, buongiorno...