name:
  - Département de démonstration
zipcode:
  - 35000
city:
  - Rennes
home_message:
  - Bienvenue dans l'espace de notre département
  - Nous vous souhaitons bienvenue dans l'ENT de notre département
