datas:
  - 1:
    first_name: Anzetoine
    last_name: Merceezier
    gender: M
  - 2:
    first_name: Sylezrvie
    last_name: Touezrrat
    gender: F
job:
  - Professeur des écoles
  - Professeur des écoles
presentation:
  - Bienvenue sur mon profil dans l'ENT
  - Chers élèves, vous pouvez communiquer avec moi depuis la messagerie
like:
  - Les bons élèves
  - L'histoire
  - La géographie
  - Les mathématiques
  - La pêche
dislike:
  - Les mauvaises notes
  - Le football
  - Le basket ball
  - Le surf
  - Faire la cuisine
  - Faire la vaisselle
status:
  - 1:
    text: Pourquoi ne pas essayer de déposer un commentaire sous ce message ?
    comments:
    - En voici un !
    - J'ai réussi à laisser un commentaire
    - Trop facile !
  - 2:
    text: J'ai découvert la campagne proche de chez moi ce week end, magnifique !
    comments:
    - Belle photo
    - Moi aussi j'aime la forêt
