gps:
  - 1:
    title: Châteaux
    places:
      - 1:
        title: Château de Versailles
        address: Chateau de Versailles
      - 2:
        title: Château de Fontainebleau
        address: Château de Fontainebleau
      - 3:
        title: Château de Chantilly
        address: Château de Chantilly Chantilly
  - 2:
    title: Villes médiévales
    places:
      - 1:
        title: Provins
        address: Provins France
      - 2:
        title: Carcassonne
        address: Carcassonne France
      - 3:
        title: La Roque-Gageac
        address: La Roque-Gageac France
  - 3:
    title: Lieux célèbres
    places:
      - 1:
        title: L'arc de triomphe
        address: Place Charles de Gaulle, 75008 Paris
      - 2:
        title: Central Park
        address: Central Park Manhattan New York
      - 3:
        title: La Sagrada Familia
        address: Sagrada Familia
  - 4:
    title: Sites touristiques
    places:
      - 1:
        title: Le Taj Mahal
        address: Taj Mahal
      - 2:
        title: Les chutes du Niagara
        address: chutes du niagara
      - 3:
        title: Stonehenge
        address: Stonehenge
  - 5:
    title: Lieux insolites
    places:
      - 1:
        title: Le Mont Rushmore
        address: 13000 S Dakota 244, Keystone, SD 57751, États-Unis
      - 2:
        title: Lac gruner See
        address: gruner See lake
      - 3:
        title: Le désert de sel salar d'Uyuni 
        address: salar d'Uyuni Bolivie