homework:
  - 1:
    subject: Géographie
    homeworks:
      - 1:
        title: Je connais 5 pays d'Europe
        content: Je sais citer 5 pays d'Europe et en dire les particularités (sur le mode de vie, les habitudes, le climat, la culture...)
        media: europe.gif
  - 2:
    subject: Sciences
    homeworks:
      - 1:
        title: Révision du vocabulaire animalier
        content: Apprendre les mots en jaune.
        media: marsupiaux.pdf
      - 2:
        title: Lecture du vocabulaire animalier
        content: Lire et découvrir les mots en jaune
        media: animaux.pdf
  - 3:
    subject: Français
    homeworks:
      - 1:
        title: Révision de la conjugaison du verbe aimer au passé composé
        content: "<p>Je connais la conjugaison d'aimer au pass&eacute; compos&eacute;, sans faute.</p>               <p>J'&eacute;cris 4 phrases avec des exemples au pass&eacute; compos&eacute;.</p>               <p>J'explique avec mes mots ce qu'est le pass&eacute; compos&eacute;.</p>"
        help: On prend les auxiliaires "avoir" ou "être" au présent et nous les faisons suivre du participe passé du verbe conjugué.
  - 4:
    subject: Lecture
    homeworks:
      - 1:
        title: Lire le chapitre 4 du livre de lecture
        content: "Je lis le chapitre 4 et je suis capable de répondre aux questions qui ? quoi ? quand ? comment ? où ?"
  - 5:
    subject: Mathématiques
    homeworks:
      - 1:
        title: Table de 4
        content: J'apprends la table de multiplication de 4 par coeur.
        help: On fait des petits papiers, d'un côté 4x1, 4x2... de l'autre la réponse. On s'entraîne (sans tricher !).
  - 6:
    subject: Histoire
    homeworks:
      - 1:
        title: Les gladiateurs
        content: Je retiens le vocabulaire.
        media: gladiateurs.pdf
  - 7:
    subject: Mathématiques
    homeworks:
      - 1:
        title: Lire l'heure
        content: Je sais différencier l'aiguille des heures et des minutes.
        media: heure.pdf
  - 8:
    subject: Culture générale
    homeworks:
      - 1:
        title: Le cinéma
        content: Je sais qui sont les frères Lumière et je cite mon film préféré.
        media: cinema.pdf
  - 9:
    subject: Education civique
    homeworks:
      - 1:
        title: Elections
        content: J'apprends le vocabulaire en jaune et je sais comment on élit le président de la République.
        media: president.pdf
  - 10:
    subject: Calcul mental
    homeworks:
      - 1:
        title: La table de 5
        content: J'apprends la table de 5 par coeur.
        help: On fait des petits papiers, d'un côté 5x1, 5x2... de l'autre la réponse. On s'entraîne (sans tricher !).
  - 11:
    subject: Sciences et vie de la terre
    homeworks:
      - 1:
        title: La forêt
        content: Je connais 3 arbres et je sais reconnaître leurs feuilles.
        media: arbres.pdf
  - 12:
    subject: Rallye lecture
    homeworks:
      - 1:
        title: Lecture
        content: Je lis le livre que j'ai choisi et je prends des notes pour répondre aux questions : qui, quoi, quand, où, comment ? Je peux présenter mon livre à la classe.
  - 13:
    subject: Conjugaison
    homeworks:
      - 1:
        title: Le passé composé
        content: Je sais conjuguer au passé composé et je sais à quoi sert ce temps. Conjuguez les verbes : manger, s'évanouir, courir, entendre et mordre.
        media: passe.pdf
  - 14:
    subject: Grammaire
    homeworks:
      - 1:
        title: La phrase et la ponctuation
        content: Je sais reconnaître une phrase et en écrire une.
  - 15:
    subject: Orthographe
    homeworks:
      - 1:
        title: Autodictée
        content: Je prépare l'autodictée niveau 1 la numéro 8.
        media: autodictee.pdf
  - 16:
    subject: Calcul
    homeworks:
      - 1:
        title: Multiplication
        content: Je pose et résous 41x4 ; 55x72 ; 6x123
  - 17:
    subject: Anglais
    homeworks:
      - 1:
        title: Je me présente
        content: Je me présente en anglais.
  - 18:
    subject: Histoire de France
    homeworks:
      - 1:
        title: Louis XIV
        content: Je sais qui est Louis XIV et j'apprends les mots en jaune.
        media: louisxiv.pdf
  - 19:
    subject: Géographie
    homeworks:
      - 1:
        title: La carte du monde
        content: Je sais placer les continents et les océans.
        media: planisphere.jpg
  - 20:
    subject: Physique
    homeworks:
      - 1:
        title: L'électricité
        content: Je sais comment fonctionne la pile électrique. Je prépare un petit exposé avec une expérience.
        media: pile.pdf
 