liaisonBook:
  - 1:
    title: La photo de classe aura lieu vendredi !
    content: "<p>Chers parents,</p>  <p>La photo de la classe des CE1 aura lieu vendredi matin, sous les cérisiers en fleur. Merci de ramener les autorisations au plus tard jeudi.&nbsp;</p>  <p>Cheese !</p>"
  - 2:
    title: Parents accompagnateurs pour la sortie au musée
    content: "<p>Chers parents,</p><p>Nous avons besoin de parents accompagnateurs pour la sortie au musée du 27 avril. Nous irons en car jusqu'à Paris pour découvrir le musée du Louvre. Nous aurions besoin de l'aide de 3 parents.</p><p>Merci !</p>"
  - 3:
    title: Sortie à la piscine
    content: "<p>Chers parents,</p><p>Tous les mardi nous allons à la piscine. Pensez à préparer le sac de votre enfant avec :</p><ul><li>une serviette de bain</li><li>un bonnet de bain</li><li>un maillot de bain</li><li>une barre de céréales ou un fruit</li><li>une petite bouteille d'eau</li><li>du gel douche</li></ul></p><p>Merci de votre attention et à bientôt !</p>"
  - 4:
    title: Attention aux poux
    content: <p>Chers parents, attention, les poux sont de retour ! V&eacute;rifiez bien la t&ecirc;te de vos enfants et n'oubliez pas les gestes simples : on ne pr&ecirc;te pas son bonnet, casquette, chouchou...&nbsp;</p> <p>Merci de votre attention !</p>
  - 5:
    title: Demandes de lots pour la kermesse de l'école
    content: <p>Chers parents,</p><p>Comme vous le savez, une kermesse est organis&eacute;e &agrave; la fin de l'ann&eacute;e. Nous cherchons des lots &agrave; offrir aux gagnants des lotos et tombolas. Si vous travaillez dans une entreprise et pouvez nous proposer des lots gratuits et adapt&eacute;s aux enfants contactez-moi via la messagerie Beneylu School.</p><p>Merci de votre g&eacute;n&eacute;rosit&eacute;.</p>
  - 6:
    title: Spectacle
    content: <p>Chers parents,&nbsp;</p><p>Les enfants ont la chance de voir le spectacle de marionnettes de la compagnie toulousaine Marion Nette mardi midi. Nous prendrons des photos ! Nous cherchons encore un parent pour nous aider &agrave; organiser ce bel &eacute;v&eacute;nement. Les volontaires peuvent m'&eacute;crire sur la messagerie Beneylu School.</p><p>Merci !</p>