minisite:
  - 1:
    banner: centre-de-loisirs-guillevic.jpg
    presentation: Notre école est fière de vous présenter son joli site internet ! Venez découvrir nos activités et la vie de notre école primaire. Nous vous souhaitons une bonne visite.
    home:
      title: Bienvenue au Centre de loisirs de Guillevic !
      content: >
        <p>Cet espace est pour vous. Nous partageons régulièrement les informations sur la vie du Centre de loisirs. Bonne visite !
        Sur ce site web, vous trouverez toutes les informations concernant le Centre de loisirs de Guillevic : où nous rencontrer, comment nous joindre, les dates importantes et toutes les actualités du centre de loisirs.</p>
      images:
        - centre-de-loisirs-guillevic.jpg
    actu:
      - 1:
        title: Initiation à la natation
        content:
          - 1:
            title: Initiation à la natation
            content: >
              <p>Bonjour à tous !
              Nous vous informons qu'une initiation à la natation aura lieu à la piscine pendant les vacances.
              Les inscriptions se font auprès des animateurs du centre. Merci !</p>
            images:
              - initiation-natation.jpg
      - 2:
        title: Evenements
        content:
          - 1:
            title: Sortie en forêt
            content: >
             <p>Nous poursuivrons notre <strong>thème de l'année sur la nature</strong> en emmenant les enfants en forêt. Ils auront la chance d'être initiés à l'accrobranche et de tester la toute nouvelle tyrolienne ! </p>
            images:
              - sortie-en-foret.jpg
          - 2:
            title: Préparation de la fête de la musique
            content: >
              <p>Bonjour à tous, nous cherchons des enfants et parents qui seraient motivés pour participer à la fête de la musique cette année ! Nous aurons une scène sur laquelle vous pourrez jouer de votre instrument favori.</p>
              <p>Amis musiciens, nous vous attendons nombreux !</p>
          - 3:
            title: Tournoi sportif au Centre de Loisirs
            content: >
              <p>Les enfants se sont dépassés pour les épreuves sportives !</p>
              <p>Félicitations aux membres de l'équipe bleue qui ont décroché le trophée au football ! </p>
            images:
              - victoire-equible-bleue.jpg
          - 4:
            title: Sortie à la ferme
            content: >
              <p>Cette année, nous avons décidé d'orienter nos activités sur le thème de la nature.</p>
              <p>Pour notre première sortie, nous avons emmené les enfants à la ferme de Gally. Ils ont eu la chance de donner à manger aux animaux !</p>
            images:
              - perruches.jpg
    pages:
      - 1:
        title: Informations Pratiques
        content: >
          <p> Où nous trouver ?<br/>
          Centre de loisirs de Guillevic<br/>
          4, allée Oscar Leroux<br/><br/>

          <strong>Secrétariat :</strong> secretariat.centre-loisirs-guillevic@gmail.com<br/><br/>

          <strong>Horaires d’ouverture en période scolaire :</strong><br/>
          LUNDI : 14H00-17H00<br/>
          MARDI : 9h00-12h00 / 14H00-19H00<br/>
          MERCREDI : 9h00-12h00 / 14H00-19H00<br/>
          JEUDI : 9h00-12h00 / 14H00-19H00<br/>
          VENDREDI : 9h00-12h00 / 14H00-19H00<br/>
          SAMEDI : 14H-18H (de novembre à avril)<br/><br/>

          <strong>Horaires d'ouverture pendants les vacances scolaires :</strong><br/>
          LUNDI : 13H30-18H30<br/>
          MARDI : 9h00-12h00 / 13H30-18H30<br/>
          MERCREDI : 9h00-12h00 / 13H30-18H30<br/>
          JEUDI : 9h00-12h00 / 13H30-18H30<br/>
          VENDREDI : 13H30-18H30<br/>
          </p>
