minisite:
  - 1:
    banner: banniere-site-web.jpg
    presentation:
    home:
      title: Accueil
      content: >
        <p>Bienvenue sur le site web de la circonscription, où vous trouverez toutes les informations et actualités concernant des écoles : scolarité, formations, actions éducatives, actualités et contacts.</p>
      images:
        - eleves-en-classe.png
    actu:
      - 1:
        title: Scolarité
        content:
          - 1:
            title: S’inscrire à l’école élémentaire
            content: >
              <p>La scolarisation des enfants est obligatoire de 6 à 16 ans.Pour inscrire vos enfants à l’école élémentaire, il faut vous renseigner auprès de la mairie.Vous connaîtrez ainsi votre école de secteur et pourrez démarrer la procédure d’inscription. <br/>Pour scolariser votre enfant dans une autre école que votre école de secteur, il faut demander une autorisation à la mairie.</p>
            images:
              - ecole-primaire-jules-ferry.jpg
          - 2:
            title: Santé scolaire
            content: >
              <p>Le service médical a pour mission de favoriser le bien-être physique, mental et social de chaque enfant scolarisé.Il s’agit aussi de détecter au plus tôt les difficultés qui pourraient gêner la profession de l’élève au cours de sa scolarité.</p><p>Le service de santé scolaire a également pour but de faciliter l’accès aux soins pour les élèves ainsi que de participer au projet santé de l’établissement et des partenaires institutionnels, territoriaux et associatifs.Dans cette perspective, le <strong>médecin scolaire assure la liaison</strong> entre l’élève, la famille, le corps enseignant et le système de prévention et de soins. Il oriente les familles vers les structures de prise en charge adaptées.</p>
            images:
              - sante-eleves-men.jpg
          - 3:
            title: Liaisons inter-degrés
            content: >
              <p>La circonscription a mis en place des liaisons inter-degrés, entre la grande section et le CP ainsi qu’entre le CM2 et la 6ème. <br/>Les petits visitent les classes des plus grands et inversement. Les élèves peuvent ainsi s’approprier le futur changement d’école. </p>
            images:
              - liaison-inter-degres.png
      - 2:
        title: Formations
        content:
          - 1:
            title: Formation Professeurs des Écoles Stagiaires
            content: >
             <p>Les enseignants de l’école élémentaire Jules Vernes organisent un forum pour les professeurs stagiaires volontaires. Les inscriptions se font auprès des directeurs d’établissement.</p><p>Les sites web du département et du ministère de l’éducation nationale proposent également des ressources concernant divers sujets :<ul><li>le numérique</li><li>la sécurité routière</li><li>l’éducation à l’alimentation</li><li>la formation aux premiers secours</li><li>la lutte contre le harcèlement</li><li>les pratiques musicales</li><li>l’activité physique</li></ul></p><p>Des formations sont disponibles tout au long de l’année dans la circonscription. Vous pouvez vous renseigner auprès de votre chef d’établissement.</p>
            images:
              - logo-education-nationale.png
          - 2:
            title: Formation au numérique
            content: >
              <p>Les écoles de la circonscription se dotent progressivement de matériel informatique pour éduquer les élèves aux nouvelles technologies.</p><p>Les enseignants qui souhaitent suivre la formation sur le numérique peuvent s’inscrire auprès du directeur d’établissement. En fonction du nombre de participants, d’autres formations seront éventuellement programmées.</p>
            images:
              - education-nouvelles-technologies.png
          - 3:
            title: Les assistants d’éducation
            content: >
              <p>Les assistants d’éducation sont des contractuels recrutés dans la fonction d’<strong>assistant d’éducation </strong> (A. E. D.) ou dans la fonction d’assistant pédagogique (A. P.).<br/>Ils exercent des fonctions d’assistance à l’équipe pédagogique. Ils peuvent se charger des missions telles que : <ul><li>la surveillance des élèves pendant le temps scolaire</li><li>l’encadrement des enfants pendant les sorties scolaires</li><li>l’animation dans les bibliothèques</li><li>l’accès aux nouvelles technologies</li><li>l’aide aux devoirs</li><li>l’aide à l’encadrement des activités culturelles, artistiques et sportives</li><li>l’accompagnement pédagogique aux élèves en difficultés (pour les A.P.)</li></ul><br/>Les assistants d’éducation peuvent <strong>suivre des formations</strong> dans le cadre de leur contrat signé avec le chef d’établissement. </p>
      - 3:
        title: Actions pédagogiques
        content:
          - 1:
            title: Le théâtre à l’école
            content: >
             <p>Dans le cadre du parcours d’éducation culturelle et artistique, les écoles de la circonscription ont mis en place un <strong>atelier d’improvisation théâtrale.</strong><br/>Largement pratiquée dans le théâtre professionnel comme amateur, l’improvisation participe à la consolidation du socle commun de connaissances, compétences et culture constitué par les programmes scolaires.<br/>L’exercice d’improvisation permet de développer l’imagination, l’écoute, l’interaction, l’adaptabilité, l’argumentation ou encore le respect de l’autre.</p><p>Renseignez-vous auprès de votre chef d’établissement pour inscrire vos classes.</p>
            images:
              - improvisation-theatrale.jpg
          - 2:
            title: L’éducation au développement durable
            content: >
              <p>Les écoles Jacques Prévert et Victor Hugo participent à un atelier pour comprendre d’où viennent les aliments. Ils se posent la question : <strong>d’où vient mon goûter ?</strong>Ils sont ainsi initiés au cycle végétal, à la production de végétaux et de lait et découvrent le métier d’agriculteur. </p><p>Ils ont également planté quelques graines dans les potagers des écoles.</p>
            images:
              - potager.png
          - 3:
            title: École sportive
            content: >
              <p>L’école Henri Barbusse a monté un projet sportif sur toute l’année. Les intervenants montrent aux élèves les bons gestes pour s’échauffer.<br/>Les enfants apprennent à échauffer leurs poignets. </p>
            images:
              - echauffement-gym.jpg
          - 4:
            title: Correspondance scolaire
            content: >
              <p>Les CM2 de l’école Jules Vernes échangent depuis le début de l’année avec une classe en Angleterre. Ils racontent la vie de leur classe, envoient des messages et des photos et apprennent l’anglais.</p>
            images:
              - correspondance-scolaire.png
    pages:
      - 1:
        title: Contacts
        content: >
          <p> Secrétariat de l’inspection :<br/>17, place du colonel Fabien <br/>Isserteaux<br/>L’inspection est ouverte du lundi au vendredi de 8h30 à 17h30, sauf pendant les vacances scolaires.<br/>Conseillère pédagogique généraliste : Mme Hurand<br/>Conseillère pédagogique EPS : Mme Petit<br/>Conseiller pédagogique TICE : M. Louaud<br/>Conseillère pédagogique Éducation Musicale : Mme Peltier<br/>Conseillère pédagogique Arts Visuels : Mme Vincent<br/>Coordonnatrice Éducation Prioritaire : Mme Pasquier<br/> Référent de scolarisation : M. Arnaud<br/></p>
