minisite:
  - 1:
    banner: banner1.jpg
    presentation: Notre école est fière de vous présenter son joli site internet ! Venez découvrir nos activités et la vie de notre école primaire. Nous vous souhaitons une bonne visite.
    home:
      title: Bienvenue
      content: >
        <p>Bienvenue à l'école primaire. Nous accueillons des enfants de 6 à 11 ans. L'école est située en région parisienne, dans les Yvelines (78). Nous sommes proches de Paris et pouvons faire des sorties culturelles régulières, mais nous pouvons aussi profiter de la cour de l'école ensoleillée et du potager des CM2 pour pique-niquer.</p>
        <p>Notre école propose de nombreuses activités : musique, piscine, chorale, sport, jardinage.</p>
      images:
        - home1.jpg
        - home2.jpg
        - home3.jpg
    actu:
      title: Les actualités
      content:
        - 1:
          title: Spectacle de marionnettes à l'école !
          content: >
            <p>Mercredi 29 avril aura lieu le spectacle de marionnette de la compagnie Marion Nette.</p>
            <p>Les enfants assisteront au spectacle le matin dans le préau. Au programme, humour, chansons et histoires fantastiques... La compagnie Marion Nette apportera des petits instruments de musique pour que les enfants participent en rythme : triangles, cymbales, grelots...</p>
            <p>Nous avons hâte d'y être !</p>
          images:
            - puppet.jpg
        - 2:
          title: Semaine de la poésie
          content: >
            <p style="text-align: justify;">La <strong>28ème semaine de la poésie</strong> sera inaugurée le 13 mars, alors à vos plumes ! Nous invitons les élèves, les parents, les enseignants et tous ceux qui le souhaitent à écrire un poème qu'il glissera dans la boîte aux lettre de l'école (dans une enveloppe). Le plus joli poème sera imprimé et affiché dans toute l'école.</p>
            <p style="text-align: justify;">Bonne chance à vous tous.</p>
            <p style="text-align: center;"><strong>L’enfance</strong></p>
            <p style="text-align: center;">&nbsp;</p>
            <p style="text-align: center;">Qu’ils étaient doux ces jours de mon enfance</p>
            <p style="text-align: center;">Où toujours gai, sans soucis, sans chagrin,</p>
            <p style="text-align: center;">je coulai ma douce existence,</p>
            <p style="text-align: center;">Sans songer au lendemain.</p>
            <p style="text-align: center;">Que me servait que tant de connaissances</p>
            <p style="text-align: center;">A mon esprit vinssent donner l’essor,</p>
            <p style="text-align: center;">On n’a pas besoin des sciences,</p>
            <p style="text-align: center;">Lorsque l’on vit dans l’âge d’or !</p>
            <p style="text-align: center;">Mon coeur encore tendre et novice,</p>
            <p style="text-align: center;">Ne connaissait pas la noirceur,</p>
            <p style="text-align: center;">De la vie en cueillant les fleurs,</p>
            <p style="text-align: center;">Je n’en sentais pas les épines,</p>
            <p style="text-align: center;">Et mes caresses enfantines</p>
            <p style="text-align: center;">Étaient pures et sans aigreurs.</p>
            <p style="text-align: center;">Croyais-je, exempt de toute peine</p>
            <p style="text-align: center;">Que, dans notre vaste univers,</p>
            <p style="text-align: center;">Tous les maux sortis des enfers,</p>
            <p style="text-align: center;">Avaient établi leur domaine ?</p>
            <p style="text-align: center;">Nous sommes loin de l’heureux temps</p>
            <p style="text-align: center;">Règne de Saturne et de Rhée,</p>
            <p style="text-align: center;">Où les vertus, les fléaux des méchants,</p>
            <p style="text-align: center;">Sur la terre étaient adorées,</p>
            <p style="text-align: center;">Car dans ces heureuses contrées</p>
            <p style="text-align: center;">Les hommes étaient des enfants.</p>
            <p style="text-align: center;"><em>Gérard de Nerval, Poésies de jeunesse</em></p>
          images:
            - sun.jpg
        - 3:
          title: Samedi 13 juin aura lieu la kermesse de l'école
          content: >
            <p>Venez nombreux à la kermesse de l'école ! Au programme, des jeux pour tous et de nombreux lots à remporter !</p>  <p>Nous avons prévu :</p>  <p>une tombola</p>  <p>une chasse au trésor dans toute la cour de récré</p>  <p>un stand de pêche aux canards&nbsp;</p>  <p>un spectacle de danse des CE1...</p>  <p>Que la fête commence !</p>
          images:
            - kermesse1.jpg
            - kermesse2.jpg
            - kermesse2.jpg
    pages:
      - 1:
        title: Ateliers de l'école
        content: >
          <h1 style="text-align: center;">L'atelier informatique des CM1 avec Mme Rose</h1>
          <p style="text-align: justify;">Mme Rose est responsable de <strong>l'atelier informatique des CM1</strong>. Chaque semaine, les enfants font des progrès en informatique (traitement de texte, recherches sur internet...) qui les aideront lors du passage au collège. Mme Rose a créé un blog pour animer l'atelier multimedia. Chaque semaine retrouvez la vidéo ou l'article de la séance, humour garanti !&nbsp;<img title="Bouche cousue" src="https://beneylu.com/ent/medias/js/tinymce/img/36x36/349.png" alt="Bouche cousue" border="0"></p>
          <h1 style="text-align: center;">Atelier danse pour les CP avec M. Grand</h1>
          <p style="text-align: justify;">Chaque mardi après le déjeuner, M. Grand emmène les CP dans le préau de l'école pour <strong>l'atelier danse</strong>. Les enfants travaillent sur deux chorégraphies pour le <strong>spectacle de fin de d'année</strong>. Les CM2 peignent les décors et préparent l'organisation du spectacle.&nbsp;</p>
        images:
          - activite1.jpg
          - activite2.jpg
      - 2:
        title: Les sorties de classe
        content: >
          <h1>Les sorties de classe</h1>
          <h1 style="text-align: center;">Sortie à la ferme avec les CE1</h1>  <p>&nbsp;</p>  <p>Mardi les CE1 sont allés à la ferme pour découvrir les animaux et le fonctionnement d'une exploitation laitière. Nous avons visité l'étable et goûté du bon lait frais. Nous avons vu la fabrication du fromage.</p>  <p>C'était super !</p>  <p>Nous préparons un exposé que nous mettrons dans le blog de l'école pour expliquer la traite des vaches.</p>
          <h1>Sortie au château de chambord avec les CM2</h1>  <p style="text-align: justify;">Les CM2 ont visité le château de Chambord lundi dernier. Ils avaient étudié au préalable l'histoire de Chambord, plus d'informations <a href="http://chambord.org/decouvrir-chambord/le-chateau/au-fil-de-lhistoire/" target="_blank">par ici</a> !</p>
        images2:
          - amboise.jpg
          - ferme1.jpg
          - ferme2.jpg
