minisite:
  - 1:
    banner: banniere-site-web-dep.jpg
    presentation: Notre école est fière de vous présenter son joli site internet ! Venez découvrir nos activités et la vie de notre école primaire. Nous vous souhaitons une bonne visite.
    home:
      title: Accueil
      content: >
        <p>Bienvenue sur le site web du département où vous trouverez toutes les informations concernant la scolarité, les formations, les actions éducatives, les actualités et les contacts.</p>
      images:
        - banniere-site-web-dep.jpg
    actu:
      - 1:
        title: scolarité
        content:
          - 1:
            title: Trouver un établissement
            content: >
              <p>Rendez-vous sur l’annuaire de l’éducation nationale pour trouver un établissement.</p>
            images:
              - potager.jpg
          - 2:
            title: Restauration scolaire
            content: >
              <p>L’éducation à l’alimentation intervient tout au long de la scolarité et permet aux élèves d’acquérir de bonnes habitudes alimentaires. Cela passe par un enseignement en classe, par des ateliers spécifiques mais aussi à la cantine.<br/>La restauration scolaire est gérée par la commune pour les écoles maternelles et élémentaires, par le département pour les collèges et par la région pour les lycées.<br/>Les plats proposés répondent à un cahier des charges stricts pour qu’ils soient variés et équilibrés tout au long de l’année.</p>
          - 3:
            title: S’inscrire au collège
            content: >
              <p>Le collège s’inscrit dans la continuité de l’école primaire et permet à chaque élève d’acquérir un socle commun de connaissances, de compétences et de culture</p>
              <p>Le dossier d'inscription en sixième est remis à l’élève par son professeur avant les vacances de printemps. Dans l'enseignement public, votre enfant sera affecté par l’inspecteur d’académie dans le collège du secteur géographique de votre domicile.</p>
          - 4:
            title: Bourses
            content: >
              <p>Des aides financières existent pour les familles aux revenus modestes. Il leur faut se renseigner auprès de la mairie pour obtenir des aides concernant la restauration, les allocations de rentrée et la fréquentation scolaire.</p>
      - 2:
        title: Actions éducatives
        content:
          - 1:
            title: Sécurité routière
            content: >
             <p>L’école a entre autres pour mission l’éducation à la citoyenneté. Ainsi, elle doit permettre aux élèves d’acquérir des comportements adéquats pour se protéger des dangers de la circulation et prendre en compte les autres usagers.<br/>Les élèves doivent donc être initiés dès le début de leur scolarité aux règles de la sécurité routière. Pour ce faire, des intervenants extérieurs peuvent aider les enseignants à mettre en place des ateliers de sensibilisation.<br/>Les écoliers et collégiens du département ont commencé leur formation en vélo avec les agents des Services publiques de la Police nationale.</p>
            images:
              - les-enfants-se-deplacent-a-velo-sur-le-circuit-permettant_2923486.jpg
          - 2:
            title: Éducation aux gestes qui sauvent
            content: >
              <p>La formation aux premiers secours est inscrite dans les programmes à partir du cycle 2. Les élèves apprennent quelques gestes qui peuvent sauver.</p>
              <p>Les élèves de CM1 de l’école Alphonse Daudet ont été initiés aux gestes de premiers secours par les Pompiers volontaires. Ils ont appris à mettre une personne inconsciente en position latérale de sécurité (PLS) et à passer un appel d’urgence.</p>
            images:
              - sortie-caserne-pompiers.png
          - 3:
            title: Rencontre avec des écrivains jeunesse
            content: >
              <p>L’école Jacques Prévert a organisé une rencontre avec 5 écrivains jeunesse. Les élèves et enseignants ont invité les collégiens et les lycéens à participer à cette rencontre riche en créativité.</p><p>Ils ont échangé autour du métier d’écrivain et de la création littéraire. Des ateliers d’écriture et de lecture ont été mis en place tout au long de la semaine.</p>
            images:
              - atelier-ecriture.jpg
          - 4:
            title: Apprendre les maths
            content: >
              <p>Plusieurs ateliers ont été mis en place dans les écoles afin de développer l’apprentissage des mathématiques.</p>
              <p>Les enseignants ont organisé des concours inter-écoles, des ateliers de programmation et des rituels mathématiques pour éveiller la curiosité mathématique chez les élèves.</p>

    pages:
      - 1:
        title: Contacts
        content: >
          <p>Conseil départemental<br/>27 rue de la République <br/>Isserteaux<br/>Ouvert au public du lundi au vendredi de 8h à 17h30.</p>
