datas:
  - 1:
    first_name: Lisa
    last_name: Bauer
    gender: F
  - 2:
    first_name: Arthur
    last_name: Combot
    gender: M
  - 3:
    first_name: Florence
    last_name: Leblanc
    gender: F
  - 4:
    first_name: Astrid
    last_name: Mayard
    gender: F
  - 5:
    first_name: Benjamin
    last_name: Bernard
    gender: M
  - 6:
    first_name: Claire
    last_name: Chetraut
    gender: F
  - 7:
    first_name: Eric
    last_name: Martin
    gender: M
  - 8:
    first_name: Florian
    last_name: Joulot
    gender: M
  - 9:
    first_name: Jules
    last_name: Sieman
    gender: M
  - 10:
    first_name: Lucile
    last_name: Figueiredo
    gender: F
  - 11:
    first_name: Marc
    last_name: Dupont
    gender: M
  - 12:
    first_name: Marie
    last_name: Valencay
    gender: F
  - 13:
    first_name: Marion
    last_name: Toulotte
    gender: F
  - 14:
    first_name: Quentin
    last_name: Durand
    gender: M
  - 15:
    first_name: Sarah
    last_name: Akmiezan
    gender: F
  - 16:
    first_name: Sophie
    last_name: Brou
    gender: F
  - 17:
    first_name: Samuel
    last_name: Brun
    gender: M
  - 18:
    first_name: Charlotte
    last_name: Hoareau
    gender: F
  - 19:
    first_name: Rafael
    last_name: Vieira
    gender: M
  - 20:
    first_name: Riya
    last_name: Yadav
    gender: F
  - 21:
    first_name: Idriss
    last_name: Yakout
    gender: M
  - 22: 
    first_name: Yuko
    last_name: Saito
    gender: F
  - 23:
    first_name: Ahmed
    last_name: Gomez
    gender: M
  - 24:
    first_name: Lou
    last_name: Muller
    gender: F
  - 25: 
    first_name: Adrien
    last_name: Sabatier
    gender: M
job:
  - Vétérinaire
  - Pilote de chasse
  - Pompier
  - Policier
  - Footballeur
  - Ingénieur informaticien
  - Avocat
  - Médecin
  - Cardiologue
  - Community manager
  - Menuisier
  - Professeur des écoles
  - Animateur informatique TICE
  - Maître nageur
  - Historien
  - Présentateur de télévision
  - Professeur de Mathématiques
  - Cascadeur
  - Infirmier
  - Juge
  - Professeur de sport
  - Ecrivain
  - Explorateur
  - Photographe animalier
  - Pediatre
presentation:
  - Je sais faire le cochon pendu et le poirier. J'aime bien notre maîtresse et aller à l'école (surtout quand on fait du sport).
  - J'ai 8 ans et demi. Je suis assez sage et j'adore le jardinage.
  - Salut ! J'ai 8 ans et j'adore le sport.
  - J'adore les histoires qui font peur et aller à la bibliothèque pour qu'on m'en raconte beaucoup.
  - J'ai 7 ans. J'adore chanter tout le temps et j'aime la chorale à l'école.
  - J'aime bien la musique et danser aussi, car ça me met de bonne humeur. Et j'ai 8 ans !
  - Hello, je suis super sympa et j'adore les animaux. Surtout les chiens et les chevaux.
  - Salut tout le monde. J'ai 7 ans et j'aime bien aller à l'école, on fait beaucoup d'activités.
  - J'aime bien les voitures, les camions de pompier et les avions aussi.
  - Bonjour. J'ai 6 ans et j'aime les bonbons. J'en mange un peu, sinon après on peut avoir des caries.
  - Salut ! Moi j'ai 8 ans, j'aime bien jouer dehors, courir et faire des gâteaux avec ma soeur.
  - Moi j'ai presque 8 ans. Je préfère quand on fait de la géographie que des maths à l'école. Sinon ça va !
  - Bonjour. J'aime les aventures et tous les jours il y en a à l'école !
  - Bonjour. J'aime bien aller à la mer et ramasser des coquillages. J'aime bien les travaux manuels en classe.
  - Salut, moi j'ai 7 ans et j'aime la poésie et les voyages.
  - Hello, moi j'aime bien aller à l'école car je peux voir mes amis et on s'amuse bien, surtout à la récré.
  - Moi j'ai 8 ans et demi et j'ai un joli chat qui s'appelle Réglisse. D'ailleurs j'aime bien les animaux.
  - Salut à tous les élèves et à la maîtresse. J'ai 8 ans et je suis fan de cinéma.
  - Bonjour à tous, j'ai 7 ans et je sais faire des tours de magie avec des cartes. C'est mon grand-père qui me les a appris.
  - Salut ! Je voudrais marcher sur la lune un jour, c'est mon rêve ! Et j'aime bien l'histoire.
  - Bonjour, j'ai 8 ans et j'aime bien écrire des histoires avec des héros et des aventures.
  - Salut, moi j'aime faire la cuisine, je sais déjà faire les gâteaux et les crêpes. C'est facile et c'est bon !
  - Hello ! J'ai voyagé aux Etats-Unis avec ma famille cet été et je connais quelques mots en anglais. J'aime bien le surf aussi, mais c'est dur.
  - Bonjour tout le monde, j'ai passé ma deuxième étoile au ski et je l'ai eue. J'aime la nature.
like:
  - Les chansons
  - Les hamburgers
  - Aller à la piscine
  - Les histoires qui font peur
  - Aller à la pêche avec mon grand-père
  - Les pâtes
  - Jouer à chat perché
  - La glace à la vanille
  - Tous les animaux
  - Les pizzas
  - Le jardinage
  - Mon chat
  - Quand il fait beau et chaud
  - Le chocolat
  - Dessiner
  - Chanter
  - Boire du jus d'orange
  - Les maths
  - Les poèmes
  - Le ketchup
  - Les chats mignons
  - Les chiens
  - Les chatons
  - Les devinettes
  - Beneylu School
  - Aller sur Internet
  - Manger du chocolat
  - Les jeux vidéos
  - Faire de la peinture
  - Les voitures
  - Le sport
  - Lire
  - Star Wars
  - Les dessins-animés
  - Le vélo
  - Le ski
  - Ma famille
  - Les vacances d'été
  - Les bonbons
  - Les anniversaires
  - Faire la fête
  - Faire du cheval
  - Le flamenco
  - Gagner
  - Les jeux de mémoire
  - La magie
  - Les devinettes
  - La plage
  - Les histoires drôles
  - Faire du roller
dislike:
  - Les mauvaises notes
  - Faire mes devoirs
  - La pluie
  - Les brocolis
  - Les disputes
  - La fin des vacances
  - Les injustices
  - Les haricots verts avec des fils
  - Les maths
  - Attendre Noël
  - Les blagues que je ne comprends pas
  - Les gens méchants
  - Quand on me gronde
  - Le vert
  - La moutarde
  - Les tomates
  - Les tortues ninja
  - La conjugaison
  - Les frites
  - Le rouge
  - Le rap
  - Les mensonges
  - La méchanceté
  - Être en colère
  - Faire des tâches sur mes vêtements
  - Les chiens méchants
  - M'ennuyer
  - Les cahiers de vacances
  - La grammaire
  - L'orthographe
  - Les jours fériés
  - La cantine
  - Le froid
  - Les coups de soleil
  - Les voleurs
  - Le orange
  - La viande
  - Etre en voiture
  - L'anglais
  - Etre malade
  - Etre en retard à l'école
  - Tomber
  - Les sodas qui piquent
  - Les chats qui griffent
  - Aller aux courses
  - Perdre mes affaires
  - Les contrôles
  - Le dentiste
  - Les endives
  - Mettre la tête sous l'eau
  
status:
  - 1:
    text: On a gagné au foot en mettant un but hier à la cantine ! Vivement le prochain match !
    comments:
    - Bravo, on gagnera encore demain
    - Heureusement que vous aviez un bon gardien
  - 2:
    text: Qu'est qui est vert qui monte et qui descend ? Un petit pois dans un ascenseur !
    comments:
    - Hahaha
    - Excellente histoire drôle
  - 3:
    text: Vivement les vacances !
    comments:
    - C'est bientôt !
    - Moi aussi j'ai hâte, mais après je m'ennuie quand même.
    image: fleur.jpg
  - 4:
    text: Aujourd'hui je suis super contente car c'est mon anniversaire ! On va manger du gâteau au goûter :-)
    comments:
    - Bon anniversaire
    - Heureux anniversaire
    - Vivement le goûter !
  - 5:
    text: Demain on va à la piscine et je vais sauter du plongeoir c'est décidé.
    comments:
    - Bonne chance !
    - Bravo, je viendrai avec toi pour t'encourager.
    - Trop fort.
  - 6:
    text: J'ai regardé Bob l'éponge , le film et c'est super drôle !
    comments:
    - Je vais le regarder avec mon grand frère alors.
    - La chance !
    - Moi j'ai pas aimé, je préfère le dessin animé.
  - 7:
    text: J'ai un rhume de printemps à cause du pollen. Atchoum !
    comments:
    - Oh pas de bol, à tes souhaits.
    - Moi aussi. Bon courage !
  - 8:
    text: J'ai finis les devoirs pour demain. L'exercice de maths était dur mais je crois que j'ai réussi.
    comments:
    - Moi j'ai pas commencé...
    - Moi non plus.
  - 9:
    text: J'ai été au skate park hier avec mon frère et y avait plein d'enfants de notre âge pour faire des jeux et du vélo. Trop cool.
    comments:
    - Je viendrai avec toi la prochaine fois si je peux.
    - Moi aussi j'y suis allé, mais en fin d'après-midi.
  - 10:
    text: Le week-end prochain mes parents nous emmène à la montagne. Je vais ramener du fromage pour goûter à l'école.
    comments:
    - Super !
    - Merci ! Prends de jolis photos aussi, tu nous montreras.
  - 11:
    text: Cet été, qui part en colo ?
    comments:
    - Moi ! En Bretagne comme l'année dernière.
    - Moi !
    - Moi non.
  - 12:
    text: On a préparé des jeux pour la kermesse.
    comments:
    - Nous on a fait des dessins et des décorations en papier coloré.
    - Moi j'ai hâte d'y être !
  - 13:
    text: J'ai finis de lire mes livres de bibliothèque. C'était super !
    comments:
    - Moi je lis Titeuf.
    - Moi j'aimerais bien lire une histoire comme Harry Potter.
  - 14:
    text: Hier j'ai vu un reportage sur Youtube sur les kangourous et ils sont mignons, sauf quand ils se battent.
    comments:
    - C'est gentil pourtant comme animal.
    - Moi j'aime bien les kangourous.
  - 15:
    text: Vous connaissez des devinettes ou des blagues ?
    comments: 
    - Deux escargots se promènent à la plage. Ils croisent une limace et se disent demi-tour, on est sur la plage des nudistes !
    - Ah ah ah ! Trop rigolo !
  - 16:
    text: Demain à la récré on organise un chat perché géant avec toutes les classes.
    comments: 
    - C'est une bonne idée !
    - Cool, je joue !
  - 17:
    text: Vous savez ce que c'est les troglodytes ?
    comments: 
    - C'est une maison dans des rochers, j'en ai vu pendant les vacances en Anjou.
    - Comme pour les nains ?
  - 18:
    text: J'aime bien écouter de la musique. J'aime bien la chanteuse Tal.
    comments: 
    - Moi aussi, j'adore, elle est trop belle en plus.
    - Moi j'aime bien chanter !
  - 19:
    text: Ma mamie m'a appris à faire de la paëlla, c'est un plat espagnol avec des moules, du poulet, du riz jaune et des crevettes.
    comments: 
    - Miam, miam !
    - J'ai déjà goûté ce plat, c'est très bon.
    - Moi j'aime pas ça.
  - 20:
    text: Vous écoutez la radio ? Moi j'écoute les infos avec mes parents des fois et ils m'expliquent.
    comments: 
    - Moi non, sauf en voiture pour chanter.
    - Avec le maître l'an dernier, on écoutait des émissions sur internet des fois. C'était intéressant.
  - 21:
    text: A votre avis, qui va gagner le match demain ? Moi je dis 1-0.
    comments: 
    - Moi je pense 1-1.
    - 5-2
  - 22:
    text: Je suis de bonne humeur, il fait beau !
    comments: 
    - Profitons du soleil !
    - Super !
  - 23:
    text: Mon poisson rouge il s'appelle Boris. Je l'ai eu ce week-end et il nage en rond dans son bocal.
    comments: 
    - Ah ah c'est marrant comme nom !
    - Moi j'ai un chat, il s'appelle Patapouf.
  - 24:
    text: Je suis tombé hier, j'ai un pansement de héros.
    comments: 
    - Ah montre !
    - Tu as dû avoir mal...
  - 25:
    text: Demain à la cantine, il y aura des spaghetti à la bolognaise et c'est mon plat préféré !
    comments: 
    - Moi aussi j'adore !
    - Moi mon plat préféré c'est les frites !