name:
  - Ecole Jean Jaurès
  - Ecole Pierre et Marie Curie
uai:
  - 123456X
  - 654321X
  - 789456X
  - 456321X
address:
  - 1 rue de la libération
  - 3 avenue Jean Jaurès
  - 18 rue de la paix
  - 14 chemin de la chapelle
  - 55 rue de Marseille
zipcode:
  - 13000
  - 69000
  - 75000
  - 59000
  - 35000
  - 44000
  - 33000
city:
  - Marseille
  - Lyon
  - Paris
  - Lille
  - Rennes
  - Nantes
  - Bordeaux
home_message:
  - Bienvenue dans l'espace de notre école
  - Nous vous souhaitons bienvenue dans l'ENT de notre école
  - Découvrez les messages que nous avons écrit dans le blog
